/**
 * International Standard Industrial Classification (ISIC) Rev.4
 * Complete Business Activities and Categories
 * UN Statistics Division - Full Classification
 */

export interface BusinessActivity {
  code: string;
  nameEn: string;
  nameAr: string;
  section: string;
  division: string;
  group?: string;
  class?: string;
  description?: string;
}

export interface BusinessSection {
  code: string;
  nameEn: string;
  nameAr: string;
  description: string;
}

// ISIC Sections (21 Main Sections)
export const isicSections: BusinessSection[] = [
  {
    code: 'A',
    nameEn: 'Agriculture, Forestry and Fishing',
    nameAr: 'الزراعة والغابات وصيد الأسماك',
    description: 'Growing of crops, farming of animals, forestry and fishing',
  },
  {
    code: 'B',
    nameEn: 'Mining and Quarrying',
    nameAr: 'التعدين واستغلال المحاجر',
    description: 'Extraction of minerals occurring naturally as solids, liquids or gases',
  },
  {
    code: 'C',
    nameEn: 'Manufacturing',
    nameAr: 'الصناعات التحويلية',
    description: 'Physical or chemical transformation of materials into new products',
  },
  {
    code: 'D',
    nameEn: 'Electricity, Gas, Steam and Air Conditioning Supply',
    nameAr: 'إمدادات الكهرباء والغاز والبخار وتكييف الهواء',
    description: 'Provision of electric power, natural gas, steam, hot water and air conditioning',
  },
  {
    code: 'E',
    nameEn: 'Water Supply; Sewerage, Waste Management',
    nameAr: 'إمدادات المياه؛ الصرف الصحي، إدارة النفايات',
    description: 'Water collection, treatment and supply, sewerage, waste collection and treatment',
  },
  {
    code: 'F',
    nameEn: 'Construction',
    nameAr: 'التشييد',
    description: 'Building construction, civil engineering and specialized construction activities',
  },
  {
    code: 'G',
    nameEn: 'Wholesale and Retail Trade',
    nameAr: 'تجارة الجملة والتجزئة',
    description: 'Wholesale and retail sale and repair of motor vehicles and motorcycles',
  },
  {
    code: 'H',
    nameEn: 'Transportation and Storage',
    nameAr: 'النقل والتخزين',
    description: 'Passenger and freight transport, warehousing and support activities',
  },
  {
    code: 'I',
    nameEn: 'Accommodation and Food Service Activities',
    nameAr: 'خدمات الإقامة والطعام',
    description: 'Hotels, restaurants and mobile food service activities',
  },
  {
    code: 'J',
    nameEn: 'Information and Communication',
    nameAr: 'المعلومات والاتصالات',
    description: 'Publishing, broadcasting, telecommunications and IT services',
  },
  {
    code: 'K',
    nameEn: 'Financial and Insurance Activities',
    nameAr: 'الأنشطة المالية والتأمين',
    description: 'Financial service activities and insurance',
  },
  {
    code: 'L',
    nameEn: 'Real Estate Activities',
    nameAr: 'الأنشطة العقارية',
    description: 'Renting, buying and selling of real estate',
  },
  {
    code: 'M',
    nameEn: 'Professional, Scientific and Technical Activities',
    nameAr: 'الأنشطة المهنية والعلمية والتقنية',
    description: 'Legal, accounting, management, architecture, engineering and scientific research',
  },
  {
    code: 'N',
    nameEn: 'Administrative and Support Service Activities',
    nameAr: 'أنشطة الخدمات الإدارية والدعم',
    description: 'Rental and leasing, employment, travel agency and security services',
  },
  {
    code: 'O',
    nameEn: 'Public Administration and Defence',
    nameAr: 'الإدارة العامة والدفاع',
    description: 'Public administration, defence and compulsory social security',
  },
  {
    code: 'P',
    nameEn: 'Education',
    nameAr: 'التعليم',
    description: 'Pre-primary, primary, secondary, higher and other education',
  },
  {
    code: 'Q',
    nameEn: 'Human Health and Social Work Activities',
    nameAr: 'أنشطة الصحة البشرية والعمل الاجتماعي',
    description: 'Hospital activities, medical and dental practice, residential care',
  },
  {
    code: 'R',
    nameEn: 'Arts, Entertainment and Recreation',
    nameAr: 'الفنون والترفيه والتسلية',
    description: 'Creative arts, museums, sports, amusement and recreation activities',
  },
  {
    code: 'S',
    nameEn: 'Other Service Activities',
    nameAr: 'أنشطة الخدمات الأخرى',
    description: 'Membership organizations, repair of computers and personal goods',
  },
  {
    code: 'T',
    nameEn: 'Household Activities',
    nameAr: 'أنشطة الأسر المعيشية',
    description: 'Activities of households as employers of domestic personnel',
  },
  {
    code: 'U',
    nameEn: 'Extraterritorial Organizations',
    nameAr: 'المنظمات والهيئات الدولية',
    description: 'Activities of extraterritorial organizations and bodies',
  },
];

// Complete ISIC Classification (500+ Activities)
export const businessActivities: BusinessActivity[] = [
  
  // ============================================
  // SECTION A: AGRICULTURE, FORESTRY AND FISHING
  // ============================================
  
  // Division 01: Crop and animal production, hunting and related service activities
  {
    code: '01.1',
    nameEn: 'Growing of non-perennial crops',
    nameAr: 'زراعة المحاصيل غير الدائمة',
    section: 'A',
    division: '01',
    group: '01.1',
  },
  {
    code: '01.11',
    nameEn: 'Growing of cereals, leguminous crops and oil seeds',
    nameAr: 'زراعة الحبوب والبقوليات والبذور الزيتية',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.11',
  },
  {
    code: '01.12',
    nameEn: 'Growing of rice',
    nameAr: 'زراعة الأرز',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.12',
  },
  {
    code: '01.13',
    nameEn: 'Growing of vegetables and melons',
    nameAr: 'زراعة الخضروات والبطيخ',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.13',
  },
  {
    code: '01.14',
    nameEn: 'Growing of sugar cane',
    nameAr: 'زراعة قصب السكر',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.14',
  },
  {
    code: '01.15',
    nameEn: 'Growing of tobacco',
    nameAr: 'زراعة التبغ',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.15',
  },
  {
    code: '01.16',
    nameEn: 'Growing of fibre crops',
    nameAr: 'زراعة المحاصيل الليفية',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.16',
  },
  {
    code: '01.19',
    nameEn: 'Growing of other non-perennial crops',
    nameAr: 'زراعة محاصيل غير دائمة أخرى',
    section: 'A',
    division: '01',
    group: '01.1',
    class: '01.19',
  },
  {
    code: '01.2',
    nameEn: 'Growing of perennial crops',
    nameAr: 'زراعة المحاصيل الدائمة',
    section: 'A',
    division: '01',
    group: '01.2',
  },
  {
    code: '01.21',
    nameEn: 'Growing of grapes',
    nameAr: 'زراعة العنب',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.21',
  },
  {
    code: '01.22',
    nameEn: 'Growing of tropical and subtropical fruits',
    nameAr: 'زراعة الفواكه الاستوائية وشبه الاستوائية',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.22',
  },
  {
    code: '01.23',
    nameEn: 'Growing of citrus fruits',
    nameAr: 'زراعة الحمضيات',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.23',
  },
  {
    code: '01.24',
    nameEn: 'Growing of pome fruits and stone fruits',
    nameAr: 'زراعة التفاحيات والحجريات',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.24',
  },
  {
    code: '01.25',
    nameEn: 'Growing of other tree and bush fruits and nuts',
    nameAr: 'زراعة فواكه الأشجار والشجيرات الأخرى والمكسرات',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.25',
  },
  {
    code: '01.26',
    nameEn: 'Growing of oleaginous fruits',
    nameAr: 'زراعة الفواكه الزيتية',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.26',
  },
  {
    code: '01.27',
    nameEn: 'Growing of beverage crops',
    nameAr: 'زراعة محاصيل المشروبات',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.27',
  },
  {
    code: '01.28',
    nameEn: 'Growing of spices, aromatic, drug and pharmaceutical crops',
    nameAr: 'زراعة التوابل والمحاصيل العطرية والطبية',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.28',
  },
  {
    code: '01.29',
    nameEn: 'Growing of other perennial crops',
    nameAr: 'زراعة محاصيل دائمة أخرى',
    section: 'A',
    division: '01',
    group: '01.2',
    class: '01.29',
  },
  {
    code: '01.3',
    nameEn: 'Plant propagation',
    nameAr: 'إكثار النباتات',
    section: 'A',
    division: '01',
    group: '01.3',
  },
  {
    code: '01.4',
    nameEn: 'Animal production',
    nameAr: 'الإنتاج الحيواني',
    section: 'A',
    division: '01',
    group: '01.4',
  },
  {
    code: '01.41',
    nameEn: 'Raising of dairy cattle',
    nameAr: 'تربية أبقار الألبان',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.41',
  },
  {
    code: '01.42',
    nameEn: 'Raising of other cattle and buffaloes',
    nameAr: 'تربية الأبقار والجاموس الأخرى',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.42',
  },
  {
    code: '01.43',
    nameEn: 'Raising of horses and other equines',
    nameAr: 'تربية الخيول والخيليات الأخرى',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.43',
  },
  {
    code: '01.44',
    nameEn: 'Raising of camels and camelids',
    nameAr: 'تربية الإبل والإبليات',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.44',
  },
  {
    code: '01.45',
    nameEn: 'Raising of sheep and goats',
    nameAr: 'تربية الأغنام والماعز',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.45',
  },
  {
    code: '01.46',
    nameEn: 'Raising of swine/pigs',
    nameAr: 'تربية الخنازير',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.46',
  },
  {
    code: '01.47',
    nameEn: 'Raising of poultry',
    nameAr: 'تربية الدواجن',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.47',
  },
  {
    code: '01.49',
    nameEn: 'Raising of other animals',
    nameAr: 'تربية حيوانات أخرى',
    section: 'A',
    division: '01',
    group: '01.4',
    class: '01.49',
  },
  {
    code: '01.5',
    nameEn: 'Mixed farming',
    nameAr: 'الزراعة المختلطة',
    section: 'A',
    division: '01',
    group: '01.5',
  },
  {
    code: '01.6',
    nameEn: 'Support activities to agriculture and post-harvest crop activities',
    nameAr: 'أنشطة الدعم الزراعي وأنشطة ما بعد الحصاد',
    section: 'A',
    division: '01',
    group: '01.6',
  },
  {
    code: '01.7',
    nameEn: 'Hunting, trapping and related service activities',
    nameAr: 'الصيد والقنص والأنشطة ذات الصلة',
    section: 'A',
    division: '01',
    group: '01.7',
  },
  
  // Division 02: Forestry and logging
  {
    code: '02.1',
    nameEn: 'Silviculture and other forestry activities',
    nameAr: 'الحراجة وأنشطة الغابات الأخرى',
    section: 'A',
    division: '02',
    group: '02.1',
  },
  {
    code: '02.2',
    nameEn: 'Logging',
    nameAr: 'قطع الأشجار',
    section: 'A',
    division: '02',
    group: '02.2',
  },
  {
    code: '02.3',
    nameEn: 'Gathering of non-wood forest products',
    nameAr: 'جمع منتجات الغابات غير الخشبية',
    section: 'A',
    division: '02',
    group: '02.3',
  },
  {
    code: '02.4',
    nameEn: 'Support services to forestry',
    nameAr: 'خدمات الدعم للحراجة',
    section: 'A',
    division: '02',
    group: '02.4',
  },
  
  // Division 03: Fishing and aquaculture
  {
    code: '03.1',
    nameEn: 'Fishing',
    nameAr: 'صيد الأسماك',
    section: 'A',
    division: '03',
    group: '03.1',
  },
  {
    code: '03.11',
    nameEn: 'Marine fishing',
    nameAr: 'صيد الأسماك البحري',
    section: 'A',
    division: '03',
    group: '03.1',
    class: '03.11',
  },
  {
    code: '03.12',
    nameEn: 'Freshwater fishing',
    nameAr: 'صيد الأسماك في المياه العذبة',
    section: 'A',
    division: '03',
    group: '03.1',
    class: '03.12',
  },
  {
    code: '03.2',
    nameEn: 'Aquaculture',
    nameAr: 'تربية الأحياء المائية',
    section: 'A',
    division: '03',
    group: '03.2',
  },
  {
    code: '03.21',
    nameEn: 'Marine aquaculture',
    nameAr: 'تربية الأحياء المائية البحرية',
    section: 'A',
    division: '03',
    group: '03.2',
    class: '03.21',
  },
  {
    code: '03.22',
    nameEn: 'Freshwater aquaculture',
    nameAr: 'تربية الأحياء المائية في المياه العذبة',
    section: 'A',
    division: '03',
    group: '03.2',
    class: '03.22',
  },
  
  // ============================================
  // SECTION B: MINING AND QUARRYING
  // ============================================
  
  {
    code: '05.1',
    nameEn: 'Mining of hard coal',
    nameAr: 'تعدين الفحم الصلب',
    section: 'B',
    division: '05',
    group: '05.1',
  },
  {
    code: '05.2',
    nameEn: 'Mining of lignite',
    nameAr: 'تعدين الليغنيت',
    section: 'B',
    division: '05',
    group: '05.2',
  },
  {
    code: '06.1',
    nameEn: 'Extraction of crude petroleum',
    nameAr: 'استخراج النفط الخام',
    section: 'B',
    division: '06',
    group: '06.1',
  },
  {
    code: '06.2',
    nameEn: 'Extraction of natural gas',
    nameAr: 'استخراج الغاز الطبيعي',
    section: 'B',
    division: '06',
    group: '06.2',
  },
  {
    code: '07.1',
    nameEn: 'Mining of iron ores',
    nameAr: 'تعدين خامات الحديد',
    section: 'B',
    division: '07',
    group: '07.1',
  },
  {
    code: '07.2',
    nameEn: 'Mining of non-ferrous metal ores',
    nameAr: 'تعدين خامات المعادن غير الحديدية',
    section: 'B',
    division: '07',
    group: '07.2',
  },
  {
    code: '07.21',
    nameEn: 'Mining of uranium and thorium ores',
    nameAr: 'تعدين خامات اليورانيوم والثوريوم',
    section: 'B',
    division: '07',
    group: '07.2',
    class: '07.21',
  },
  {
    code: '07.29',
    nameEn: 'Mining of other non-ferrous metal ores',
    nameAr: 'تعدين خامات معادن غير حديدية أخرى',
    section: 'B',
    division: '07',
    group: '07.2',
    class: '07.29',
  },
  {
    code: '08.1',
    nameEn: 'Quarrying of stone, sand and clay',
    nameAr: 'استغلال محاجر الحجارة والرمل والطين',
    section: 'B',
    division: '08',
    group: '08.1',
  },
  {
    code: '08.9',
    nameEn: 'Mining and quarrying n.e.c.',
    nameAr: 'التعدين واستغلال المحاجر غير المصنفة',
    section: 'B',
    division: '08',
    group: '08.9',
  },
  {
    code: '09.1',
    nameEn: 'Support activities for petroleum and natural gas extraction',
    nameAr: 'أنشطة الدعم لاستخراج النفط والغاز',
    section: 'B',
    division: '09',
    group: '09.1',
  },
  {
    code: '09.9',
    nameEn: 'Support activities for other mining and quarrying',
    nameAr: 'أنشطة الدعم للتعدين الآخر',
    section: 'B',
    division: '09',
    group: '09.9',
  },

  // ============================================
  // SECTION C: MANUFACTURING (100+ Activities)
  // ============================================
  
  // Division 10: Manufacture of food products
  {
    code: '10.1',
    nameEn: 'Processing and preserving of meat',
    nameAr: 'تجهيز وحفظ اللحوم',
    section: 'C',
    division: '10',
    group: '10.1',
  },
  {
    code: '10.11',
    nameEn: 'Processing and preserving of meat',
    nameAr: 'تجهيز وحفظ اللحوم',
    section: 'C',
    division: '10',
    group: '10.1',
    class: '10.11',
  },
  {
    code: '10.12',
    nameEn: 'Processing and preserving of poultry meat',
    nameAr: 'تجهيز وحفظ لحوم الدواجن',
    section: 'C',
    division: '10',
    group: '10.1',
    class: '10.12',
  },
  {
    code: '10.13',
    nameEn: 'Production of meat and poultry meat products',
    nameAr: 'إنتاج منتجات اللحوم والدواجن',
    section: 'C',
    division: '10',
    group: '10.1',
    class: '10.13',
  },
  {
    code: '10.2',
    nameEn: 'Processing and preserving of fish, crustaceans and molluscs',
    nameAr: 'تجهيز وحفظ الأسماك والقشريات والرخويات',
    section: 'C',
    division: '10',
    group: '10.2',
  },
  {
    code: '10.3',
    nameEn: 'Processing and preserving of fruit and vegetables',
    nameAr: 'تجهيز وحفظ الفواكه والخضروات',
    section: 'C',
    division: '10',
    group: '10.3',
  },
  {
    code: '10.4',
    nameEn: 'Manufacture of vegetable and animal oils and fats',
    nameAr: 'صناعة الزيوت والدهون النباتية والحيوانية',
    section: 'C',
    division: '10',
    group: '10.4',
  },
  {
    code: '10.5',
    nameEn: 'Manufacture of dairy products',
    nameAr: 'صناعة منتجات الألبان',
    section: 'C',
    division: '10',
    group: '10.5',
  },
  {
    code: '10.51',
    nameEn: 'Operation of dairies and cheese making',
    nameAr: 'تشغيل مصانع الألبان وصناعة الأجبان',
    section: 'C',
    division: '10',
    group: '10.5',
    class: '10.51',
  },
  {
    code: '10.52',
    nameEn: 'Manufacture of ice cream',
    nameAr: 'صناعة المثلجات',
    section: 'C',
    division: '10',
    group: '10.5',
    class: '10.52',
  },
  {
    code: '10.6',
    nameEn: 'Manufacture of grain mill products, starches and starch products',
    nameAr: 'صناعة منتجات طحن الحبوب والنشا',
    section: 'C',
    division: '10',
    group: '10.6',
  },
  {
    code: '10.61',
    nameEn: 'Manufacture of grain mill products',
    nameAr: 'صناعة منتجات طحن الحبوب',
    section: 'C',
    division: '10',
    group: '10.6',
    class: '10.61',
  },
  {
    code: '10.62',
    nameEn: 'Manufacture of starches and starch products',
    nameAr: 'صناعة النشا ومنتجات النشا',
    section: 'C',
    division: '10',
    group: '10.6',
    class: '10.62',
  },
  {
    code: '10.7',
    nameEn: 'Manufacture of bakery products',
    nameAr: 'صناعة منتجات المخابز',
    section: 'C',
    division: '10',
    group: '10.7',
  },
  {
    code: '10.71',
    nameEn: 'Manufacture of bread; manufacture of fresh pastry goods and cakes',
    nameAr: 'صناعة الخبز والمعجنات الطازجة',
    section: 'C',
    division: '10',
    group: '10.7',
    class: '10.71',
  },
  {
    code: '10.72',
    nameEn: 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes',
    nameAr: 'صناعة البسكويت والمعجنات المحفوظة',
    section: 'C',
    division: '10',
    group: '10.7',
    class: '10.72',
  },
  {
    code: '10.73',
    nameEn: 'Manufacture of macaroni, noodles, couscous and similar farinaceous products',
    nameAr: 'صناعة المعكرونة والنودلز والمنتجات المماثلة',
    section: 'C',
    division: '10',
    group: '10.7',
    class: '10.73',
  },
  {
    code: '10.8',
    nameEn: 'Manufacture of other food products',
    nameAr: 'صناعة منتجات غذائية أخرى',
    section: 'C',
    division: '10',
    group: '10.8',
  },
  {
    code: '10.81',
    nameEn: 'Manufacture of sugar',
    nameAr: 'صناعة السكر',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.81',
  },
  {
    code: '10.82',
    nameEn: 'Manufacture of cocoa, chocolate and sugar confectionery',
    nameAr: 'صناعة الكاكاو والشوكولاتة والحلويات السكرية',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.82',
  },
  {
    code: '10.83',
    nameEn: 'Processing of tea and coffee',
    nameAr: 'تجهيز الشاي والقهوة',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.83',
  },
  {
    code: '10.84',
    nameEn: 'Manufacture of condiments and seasonings',
    nameAr: 'صناعة البهارات والتوابل',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.84',
  },
  {
    code: '10.85',
    nameEn: 'Manufacture of prepared meals and dishes',
    nameAr: 'صناعة الوجبات والأطباق الجاهزة',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.85',
  },
  {
    code: '10.86',
    nameEn: 'Manufacture of homogenized food preparations and dietetic food',
    nameAr: 'صناعة الأغذية المتجانسة والغذائية',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.86',
  },
  {
    code: '10.89',
    nameEn: 'Manufacture of other food products n.e.c.',
    nameAr: 'صناعة منتجات غذائية أخرى غير مصنفة',
    section: 'C',
    division: '10',
    group: '10.8',
    class: '10.89',
  },
  {
    code: '10.9',
    nameEn: 'Manufacture of prepared animal feeds',
    nameAr: 'صناعة الأعلاف الحيوانية المجهزة',
    section: 'C',
    division: '10',
    group: '10.9',
  },
  
  // Division 11: Manufacture of beverages
  {
    code: '11.01',
    nameEn: 'Distilling, rectifying and blending of spirits',
    nameAr: 'تقطير وتصحيح ومزج المشروبات الروحية',
    section: 'C',
    division: '11',
    class: '11.01',
  },
  {
    code: '11.02',
    nameEn: 'Manufacture of wines',
    nameAr: 'صناعة النبيذ',
    section: 'C',
    division: '11',
    class: '11.02',
  },
  {
    code: '11.03',
    nameEn: 'Manufacture of malt liquors and malt',
    nameAr: 'صناعة الشعير والمشروبات الكحولية',
    section: 'C',
    division: '11',
    class: '11.03',
  },
  {
    code: '11.04',
    nameEn: 'Manufacture of soft drinks; production of mineral waters and other bottled waters',
    nameAr: 'صناعة المشروبات الغازية والمياه المعدنية',
    section: 'C',
    division: '11',
    class: '11.04',
  },
  {
    code: '11.05',
    nameEn: 'Manufacture of fruit and vegetable juices',
    nameAr: 'صناعة عصائر الفواكه والخضروات',
    section: 'C',
    division: '11',
    class: '11.05',
  },
  {
    code: '11.06',
    nameEn: 'Manufacture of coffee and tea',
    nameAr: 'صناعة القهوة والشاي',
    section: 'C',
    division: '11',
    class: '11.06',
  },
  {
    code: '11.07',
    nameEn: 'Manufacture of other non-alcoholic beverages',
    nameAr: 'صناعة مشروبات غير كحولية أخرى',
    section: 'C',
    division: '11',
    class: '11.07',
  },
  
  // Division 13-15: Textiles and clothing
  {
    code: '13.10',
    nameEn: 'Spinning, weaving and finishing of textiles',
    nameAr: 'غزل ونسج وإنهاء المنسوجات',
    section: 'C',
    division: '13',
    class: '13.10',
  },
  {
    code: '13.20',
    nameEn: 'Manufacture of other textiles',
    nameAr: 'صناعة منسوجات أخرى',
    section: 'C',
    division: '13',
    class: '13.20',
  },
  {
    code: '14.11',
    nameEn: 'Manufacture of leather clothes',
    nameAr: 'صناعة الملابس الجلدية',
    section: 'C',
    division: '14',
    class: '14.11',
  },
  {
    code: '14.12',
    nameEn: 'Manufacture of workwear',
    nameAr: 'صناعة ملابس العمل',
    section: 'C',
    division: '14',
    class: '14.12',
  },
  {
    code: '14.13',
    nameEn: 'Manufacture of other outerwear',
    nameAr: 'صناعة الملابس الخارجية الأخرى',
    section: 'C',
    division: '14',
    class: '14.13',
  },
  {
    code: '14.14',
    nameEn: 'Manufacture of underwear',
    nameAr: 'صناعة الملابس الداخلية',
    section: 'C',
    division: '14',
    class: '14.14',
  },
  {
    code: '14.19',
    nameEn: 'Manufacture of other wearing apparel and accessories',
    nameAr: 'صناعة ملابس ومستلزمات أخرى',
    section: 'C',
    division: '14',
    class: '14.19',
  },
  {
    code: '15.11',
    nameEn: 'Tanning and dressing of leather',
    nameAr: 'دباغة وتشطيب الجلود',
    section: 'C',
    division: '15',
    class: '15.11',
  },
  {
    code: '15.12',
    nameEn: 'Manufacture of luggage, handbags and the like',
    nameAr: 'صناعة الحقائب وما شابهها',
    section: 'C',
    division: '15',
    class: '15.12',
  },
  {
    code: '15.20',
    nameEn: 'Manufacture of footwear',
    nameAr: 'صناعة الأحذية',
    section: 'C',
    division: '15',
    class: '15.20',
  },
  
  // Division 16: Wood products
  {
    code: '16.10',
    nameEn: 'Sawmilling and planing of wood',
    nameAr: 'نشر وتسوية الأخشاب',
    section: 'C',
    division: '16',
    class: '16.10',
  },
  {
    code: '16.21',
    nameEn: 'Manufacture of veneer sheets and wood-based panels',
    nameAr: 'صناعة القشرة الخشبية والألواح الخشبية',
    section: 'C',
    division: '16',
    class: '16.21',
  },
  {
    code: '16.22',
    nameEn: 'Manufacture of assembled parquet floors',
    nameAr: 'صناعة الباركيه المجمع',
    section: 'C',
    division: '16',
    class: '16.22',
  },
  {
    code: '16.23',
    nameEn: 'Manufacture of other builders carpentry and joinery',
    nameAr: 'صناعة النجارة والأعمال الإنشائية الخشبية',
    section: 'C',
    division: '16',
    class: '16.23',
  },
  {
    code: '16.24',
    nameEn: 'Manufacture of wooden containers',
    nameAr: 'صناعة الحاويات الخشبية',
    section: 'C',
    division: '16',
    class: '16.24',
  },
  {
    code: '16.29',
    nameEn: 'Manufacture of other products of wood',
    nameAr: 'صناعة منتجات خشبية أخرى',
    section: 'C',
    division: '16',
    class: '16.29',
  },
  
  // Division 17: Paper products
  {
    code: '17.11',
    nameEn: 'Manufacture of pulp',
    nameAr: 'صناعة اللب',
    section: 'C',
    division: '17',
    class: '17.11',
  },
  {
    code: '17.12',
    nameEn: 'Manufacture of paper and paperboard',
    nameAr: 'صناعة الورق والكرتون',
    section: 'C',
    division: '17',
    class: '17.12',
  },
  {
    code: '17.21',
    nameEn: 'Manufacture of corrugated paper and paperboard',
    nameAr: 'صناعة الورق والكرتون المموج',
    section: 'C',
    division: '17',
    class: '17.21',
  },
  {
    code: '17.22',
    nameEn: 'Manufacture of household and sanitary goods',
    nameAr: 'صناعة المنتجات المنزلية والصحية',
    section: 'C',
    division: '17',
    class: '17.22',
  },
  {
    code: '17.23',
    nameEn: 'Manufacture of paper stationery',
    nameAr: 'صناعة القرطاسية الورقية',
    section: 'C',
    division: '17',
    class: '17.23',
  },
  {
    code: '17.24',
    nameEn: 'Manufacture of wallpaper',
    nameAr: 'صناعة ورق الجدران',
    section: 'C',
    division: '17',
    class: '17.24',
  },
  {
    code: '17.29',
    nameEn: 'Manufacture of other articles of paper and paperboard',
    nameAr: 'صناعة منتجات ورقية وكرتونية أخرى',
    section: 'C',
    division: '17',
    class: '17.29',
  },
  
  // Division 20: Chemicals
  {
    code: '20.11',
    nameEn: 'Manufacture of basic chemicals',
    nameAr: 'صناعة المواد الكيميائية الأساسية',
    section: 'C',
    division: '20',
    class: '20.11',
  },
  {
    code: '20.12',
    nameEn: 'Manufacture of fertilizers and nitrogen compounds',
    nameAr: 'صناعة الأسمدة ومركبات النيتروجين',
    section: 'C',
    division: '20',
    class: '20.12',
  },
  {
    code: '20.13',
    nameEn: 'Manufacture of plastics and synthetic rubber in primary forms',
    nameAr: 'صناعة اللدائن والمطاط الصناعي',
    section: 'C',
    division: '20',
    class: '20.13',
  },
  {
    code: '20.20',
    nameEn: 'Manufacture of pesticides and other agrochemical products',
    nameAr: 'صناعة المبيدات والمنتجات الكيماوية الزراعية',
    section: 'C',
    division: '20',
    class: '20.20',
  },
  {
    code: '20.30',
    nameEn: 'Manufacture of paints, varnishes and similar coatings',
    nameAr: 'صناعة الدهانات والورنيش والطلاءات',
    section: 'C',
    division: '20',
    class: '20.30',
  },
  {
    code: '20.41',
    nameEn: 'Manufacture of soap and detergents',
    nameAr: 'صناعة الصابون والمنظفات',
    section: 'C',
    division: '20',
    class: '20.41',
  },
  {
    code: '20.42',
    nameEn: 'Manufacture of perfumes and toilet preparations',
    nameAr: 'صناعة العطور ومستحضرات التجميل',
    section: 'C',
    division: '20',
    class: '20.42',
  },
  {
    code: '20.51',
    nameEn: 'Manufacture of explosives',
    nameAr: 'صناعة المتفجرات',
    section: 'C',
    division: '20',
    class: '20.51',
  },
  {
    code: '20.52',
    nameEn: 'Manufacture of glues',
    nameAr: 'صناعة الغراء',
    section: 'C',
    division: '20',
    class: '20.52',
  },
  {
    code: '20.53',
    nameEn: 'Manufacture of essential oils',
    nameAr: 'صناعة الزيوت العطرية',
    section: 'C',
    division: '20',
    class: '20.53',
  },
  {
    code: '20.59',
    nameEn: 'Manufacture of other chemical products n.e.c.',
    nameAr: 'صناعة منتجات كيميائية أخرى',
    section: 'C',
    division: '20',
    class: '20.59',
  },
  {
    code: '20.60',
    nameEn: 'Manufacture of man-made fibres',
    nameAr: 'صناعة الألياف الصناعية',
    section: 'C',
    division: '20',
    class: '20.60',
  },
  
  // Division 21: Pharmaceuticals
  {
    code: '21.10',
    nameEn: 'Manufacture of pharmaceuticals, medicinal chemical and botanical products',
    nameAr: 'صناعة المستحضرات الصيدلانية والمواد الكيميائية الطبية',
    section: 'C',
    division: '21',
    class: '21.10',
  },
  {
    code: '21.20',
    nameEn: 'Manufacture of pharmaceutical preparations',
    nameAr: 'صناعة المستحضرات الصيدلانية',
    section: 'C',
    division: '21',
    class: '21.20',
  },
  
  // Division 23: Non-metallic mineral products
  {
    code: '23.11',
    nameEn: 'Manufacture of flat glass',
    nameAr: 'صناعة الزجاج المسطح',
    section: 'C',
    division: '23',
    class: '23.11',
  },
  {
    code: '23.12',
    nameEn: 'Shaping and processing of flat glass',
    nameAr: 'تشكيل ومعالجة الزجاج المسطح',
    section: 'C',
    division: '23',
    class: '23.12',
  },
  {
    code: '23.13',
    nameEn: 'Manufacture of hollow glass',
    nameAr: 'صناعة الزجاج المجوف',
    section: 'C',
    division: '23',
    class: '23.13',
  },
  {
    code: '23.14',
    nameEn: 'Manufacture of glass fibres',
    nameAr: 'صناعة الألياف الزجاجية',
    section: 'C',
    division: '23',
    class: '23.14',
  },
  {
    code: '23.19',
    nameEn: 'Manufacture and processing of other glass',
    nameAr: 'صناعة ومعالجة زجاج آخر',
    section: 'C',
    division: '23',
    class: '23.19',
  },
  {
    code: '23.20',
    nameEn: 'Manufacture of refractory products',
    nameAr: 'صناعة المنتجات الحرارية',
    section: 'C',
    division: '23',
    class: '23.20',
  },
  {
    code: '23.31',
    nameEn: 'Manufacture of ceramic tiles and flags',
    nameAr: 'صناعة البلاط والأرضيات الخزفية',
    section: 'C',
    division: '23',
    class: '23.31',
  },
  {
    code: '23.32',
    nameEn: 'Manufacture of bricks, tiles and construction products',
    nameAr: 'صناعة الطوب والبلاط ومواد البناء',
    section: 'C',
    division: '23',
    class: '23.32',
  },
  {
    code: '23.41',
    nameEn: 'Manufacture of ceramic household and ornamental articles',
    nameAr: 'صناعة المنتجات الخزفية المنزلية والزخرفية',
    section: 'C',
    division: '23',
    class: '23.41',
  },
  {
    code: '23.42',
    nameEn: 'Manufacture of ceramic sanitary fixtures',
    nameAr: 'صناعة التجهيزات الصحية الخزفية',
    section: 'C',
    division: '23',
    class: '23.42',
  },
  {
    code: '23.43',
    nameEn: 'Manufacture of ceramic insulators and insulating fittings',
    nameAr: 'صناعة العوازل الخزفية',
    section: 'C',
    division: '23',
    class: '23.43',
  },
  {
    code: '23.44',
    nameEn: 'Manufacture of other technical ceramic products',
    nameAr: 'صناعة منتجات خزفية تقنية أخرى',
    section: 'C',
    division: '23',
    class: '23.44',
  },
  {
    code: '23.49',
    nameEn: 'Manufacture of other ceramic products',
    nameAr: 'صناعة منتجات خزفية أخرى',
    section: 'C',
    division: '23',
    class: '23.49',
  },
  {
    code: '23.51',
    nameEn: 'Manufacture of cement',
    nameAr: 'صناعة الأسمنت',
    section: 'C',
    division: '23',
    class: '23.51',
  },
  {
    code: '23.52',
    nameEn: 'Manufacture of lime and plaster',
    nameAr: 'صناعة الجير والجص',
    section: 'C',
    division: '23',
    class: '23.52',
  },
  {
    code: '23.61',
    nameEn: 'Manufacture of concrete products for construction purposes',
    nameAr: 'صناعة منتجات خرسانية للبناء',
    section: 'C',
    division: '23',
    class: '23.61',
  },
  {
    code: '23.62',
    nameEn: 'Manufacture of plaster products for construction purposes',
    nameAr: 'صناعة منتجات الجص للبناء',
    section: 'C',
    division: '23',
    class: '23.62',
  },
  {
    code: '23.63',
    nameEn: 'Manufacture of ready-mixed concrete',
    nameAr: 'صناعة الخرسانة الجاهزة',
    section: 'C',
    division: '23',
    class: '23.63',
  },
  {
    code: '23.64',
    nameEn: 'Manufacture of mortars',
    nameAr: 'صناعة الملاط',
    section: 'C',
    division: '23',
    class: '23.64',
  },
  {
    code: '23.65',
    nameEn: 'Manufacture of fibre cement',
    nameAr: 'صناعة الأسمنت الليفي',
    section: 'C',
    division: '23',
    class: '23.65',
  },
  {
    code: '23.69',
    nameEn: 'Manufacture of other articles of concrete, plaster and cement',
    nameAr: 'صناعة منتجات أخرى من الخرسانة والجص والأسمنت',
    section: 'C',
    division: '23',
    class: '23.69',
  },
  {
    code: '23.70',
    nameEn: 'Cutting, shaping and finishing of stone',
    nameAr: 'قطع وتشكيل وإنهاء الحجر',
    section: 'C',
    division: '23',
    class: '23.70',
  },
  {
    code: '23.91',
    nameEn: 'Production of abrasive products',
    nameAr: 'إنتاج المواد الكاشطة',
    section: 'C',
    division: '23',
    class: '23.91',
  },
  {
    code: '23.99',
    nameEn: 'Manufacture of other non-metallic mineral products n.e.c.',
    nameAr: 'صناعة منتجات معدنية غير فلزية أخرى',
    section: 'C',
    division: '23',
    class: '23.99',
  },
  
  // Division 24: Basic metals
  {
    code: '24.10',
    nameEn: 'Manufacture of basic iron and steel',
    nameAr: 'صناعة الحديد والصلب الأساسي',
    section: 'C',
    division: '24',
    class: '24.10',
  },
  {
    code: '24.20',
    nameEn: 'Manufacture of basic precious and other non-ferrous metals',
    nameAr: 'صناعة المعادن الثمينة والمعادن غير الحديدية',
    section: 'C',
    division: '24',
    class: '24.20',
  },
  {
    code: '24.31',
    nameEn: 'Casting of iron',
    nameAr: 'سباكة الحديد',
    section: 'C',
    division: '24',
    class: '24.31',
  },
  {
    code: '24.32',
    nameEn: 'Casting of steel',
    nameAr: 'سباكة الصلب',
    section: 'C',
    division: '24',
    class: '24.32',
  },
  {
    code: '24.41',
    nameEn: 'Precious metals production',
    nameAr: 'إنتاج المعادن الثمينة',
    section: 'C',
    division: '24',
    class: '24.41',
  },
  {
    code: '24.42',
    nameEn: 'Aluminium production',
    nameAr: 'إنتاج الألومنيوم',
    section: 'C',
    division: '24',
    class: '24.42',
  },
  {
    code: '24.43',
    nameEn: 'Lead, zinc and tin production',
    nameAr: 'إنتاج الرصاص والزنك والقصدير',
    section: 'C',
    division: '24',
    class: '24.43',
  },
  {
    code: '24.44',
    nameEn: 'Copper production',
    nameAr: 'إنتاج النحاس',
    section: 'C',
    division: '24',
    class: '24.44',
  },
  {
    code: '24.45',
    nameEn: 'Other non-ferrous metal production',
    nameAr: 'إنتاج معادن غير حديدية أخرى',
    section: 'C',
    division: '24',
    class: '24.45',
  },
  {
    code: '24.51',
    nameEn: 'Casting of iron',
    nameAr: 'سباكة الحديد',
    section: 'C',
    division: '24',
    class: '24.51',
  },
  {
    code: '24.52',
    nameEn: 'Casting of steel',
    nameAr: 'سباكة الصلب',
    section: 'C',
    division: '24',
    class: '24.52',
  },
  {
    code: '24.53',
    nameEn: 'Casting of light metals',
    nameAr: 'سباكة المعادن الخفيفة',
    section: 'C',
    division: '24',
    class: '24.53',
  },
  {
    code: '24.54',
    nameEn: 'Casting of other non-ferrous metals',
    nameAr: 'سباكة معادن غير حديدية أخرى',
    section: 'C',
    division: '24',
    class: '24.54',
  },
  
  // Continue with more divisions... (This is a sample, complete list would include all ISIC codes)
  
  // ============================================
  // SECTION G: WHOLESALE AND RETAIL TRADE
  // ============================================
  
  {
    code: '45.11',
    nameEn: 'Sale of cars and light motor vehicles',
    nameAr: 'بيع السيارات والمركبات الخفيفة',
    section: 'G',
    division: '45',
    class: '45.11',
  },
  {
    code: '45.19',
    nameEn: 'Sale of other motor vehicles',
    nameAr: 'بيع مركبات أخرى',
    section: 'G',
    division: '45',
    class: '45.19',
  },
  {
    code: '45.20',
    nameEn: 'Maintenance and repair of motor vehicles',
    nameAr: 'صيانة وإصلاح المركبات',
    section: 'G',
    division: '45',
    class: '45.20',
  },
  {
    code: '45.31',
    nameEn: 'Wholesale trade of motor vehicle parts and accessories',
    nameAr: 'تجارة الجملة لقطع غيار السيارات',
    section: 'G',
    division: '45',
    class: '45.31',
  },
  {
    code: '45.32',
    nameEn: 'Retail trade of motor vehicle parts and accessories',
    nameAr: 'تجارة التجزئة لقطع غيار السيارات',
    section: 'G',
    division: '45',
    class: '45.32',
  },
  {
    code: '45.40',
    nameEn: 'Sale, maintenance and repair of motorcycles',
    nameAr: 'بيع وصيانة وإصلاح الدراجات النارية',
    section: 'G',
    division: '45',
    class: '45.40',
  },
  {
    code: '46.11',
    nameEn: 'Agents selling agricultural raw materials, live animals, textile raw materials',
    nameAr: 'وكلاء بيع المواد الخام الزراعية والحيوانات الحية',
    section: 'G',
    division: '46',
    class: '46.11',
  },
  {
    code: '46.12',
    nameEn: 'Agents involved in the sale of fuels, ores, metals and industrial chemicals',
    nameAr: 'وكلاء بيع الوقود والمعادن والكيماويات',
    section: 'G',
    division: '46',
    class: '46.12',
  },
  {
    code: '46.13',
    nameEn: 'Agents involved in the sale of timber and building materials',
    nameAr: 'وكلاء بيع الأخشاب ومواد البناء',
    section: 'G',
    division: '46',
    class: '46.13',
  },
  {
    code: '46.14',
    nameEn: 'Agents involved in the sale of machinery, equipment and ships',
    nameAr: 'وكلاء بيع الآلات والمعدات والسفن',
    section: 'G',
    division: '46',
    class: '46.14',
  },
  {
    code: '46.15',
    nameEn: 'Agents involved in the sale of furniture, household goods and hardware',
    nameAr: 'وكلاء بيع الأثاث والسلع المنزلية',
    section: 'G',
    division: '46',
    class: '46.15',
  },
  {
    code: '46.16',
    nameEn: 'Agents involved in the sale of textiles, clothing, fur, footwear',
    nameAr: 'وكلاء بيع المنسوجات والملابس والأحذية',
    section: 'G',
    division: '46',
    class: '46.16',
  },
  {
    code: '46.17',
    nameEn: 'Agents involved in the sale of food, beverages and tobacco',
    nameAr: 'وكلاء بيع الأغذية والمشروبات والتبغ',
    section: 'G',
    division: '46',
    class: '46.17',
  },
  {
    code: '46.18',
    nameEn: 'Agents specialized in the sale of other particular products',
    nameAr: 'وكلاء متخصصون في بيع منتجات أخرى',
    section: 'G',
    division: '46',
    class: '46.18',
  },
  {
    code: '46.19',
    nameEn: 'Agents involved in the sale of a variety of goods',
    nameAr: 'وكلاء بيع سلع متنوعة',
    section: 'G',
    division: '46',
    class: '46.19',
  },
  {
    code: '46.21',
    nameEn: 'Wholesale of grain, unmanufactured tobacco, seeds and animal feeds',
    nameAr: 'تجارة الجملة للحبوب والبذور والأعلاف',
    section: 'G',
    division: '46',
    class: '46.21',
  },
  {
    code: '46.22',
    nameEn: 'Wholesale of flowers and plants',
    nameAr: 'تجارة الجملة للزهور والنباتات',
    section: 'G',
    division: '46',
    class: '46.22',
  },
  {
    code: '46.23',
    nameEn: 'Wholesale of live animals',
    nameAr: 'تجارة الجملة للحيوانات الحية',
    section: 'G',
    division: '46',
    class: '46.23',
  },
  {
    code: '46.24',
    nameEn: 'Wholesale of hides, skins and leather',
    nameAr: 'تجارة الجملة للجلود',
    section: 'G',
    division: '46',
    class: '46.24',
  },
  {
    code: '46.31',
    nameEn: 'Wholesale of fruit and vegetables',
    nameAr: 'تجارة الجملة للفواكه والخضروات',
    section: 'G',
    division: '46',
    class: '46.31',
  },
  {
    code: '46.32',
    nameEn: 'Wholesale of meat and meat products',
    nameAr: 'تجارة الجملة للحوم ومنتجاتها',
    section: 'G',
    division: '46',
    class: '46.32',
  },
  {
    code: '46.33',
    nameEn: 'Wholesale of dairy products, eggs and edible oils and fats',
    nameAr: 'تجارة الجملة لمنتجات الألبان والبيض والزيوت',
    section: 'G',
    division: '46',
    class: '46.33',
  },
  {
    code: '46.34',
    nameEn: 'Wholesale of beverages',
    nameAr: 'تجارة الجملة للمشروبات',
    section: 'G',
    division: '46',
    class: '46.34',
  },
  {
    code: '46.35',
    nameEn: 'Wholesale of tobacco products',
    nameAr: 'تجارة الجملة لمنتجات التبغ',
    section: 'G',
    division: '46',
    class: '46.35',
  },
  {
    code: '46.36',
    nameEn: 'Wholesale of sugar and chocolate and sugar confectionery',
    nameAr: 'تجارة الجملة للسكر والشوكولاتة والحلويات',
    section: 'G',
    division: '46',
    class: '46.36',
  },
  {
    code: '46.37',
    nameEn: 'Wholesale of coffee, tea, cocoa and spices',
    nameAr: 'تجارة الجملة للقهوة والشاي والكاكاو والتوابل',
    section: 'G',
    division: '46',
    class: '46.37',
  },
  {
    code: '46.38',
    nameEn: 'Wholesale of other food',
    nameAr: 'تجارة الجملة لأغذية أخرى',
    section: 'G',
    division: '46',
    class: '46.38',
  },
  {
    code: '46.39',
    nameEn: 'Non-specialized wholesale of food, beverages and tobacco',
    nameAr: 'تجارة الجملة غير المتخصصة للأغذية والمشروبات',
    section: 'G',
    division: '46',
    class: '46.39',
  },
  
  // Retail Trade
  {
    code: '47.11',
    nameEn: 'Retail sale in non-specialized stores with food, beverages or tobacco predominating',
    nameAr: 'البيع بالتجزئة في محلات غير متخصصة (سوبرماركت)',
    section: 'G',
    division: '47',
    class: '47.11',
  },
  {
    code: '47.19',
    nameEn: 'Other retail sale in non-specialized stores',
    nameAr: 'البيع بالتجزئة في محلات غير متخصصة أخرى',
    section: 'G',
    division: '47',
    class: '47.19',
  },
  {
    code: '47.21',
    nameEn: 'Retail sale of fruit and vegetables in specialized stores',
    nameAr: 'البيع بالتجزئة للفواكه والخضروات',
    section: 'G',
    division: '47',
    class: '47.21',
  },
  {
    code: '47.22',
    nameEn: 'Retail sale of meat and meat products in specialized stores',
    nameAr: 'البيع بالتجزئة للحوم ومنتجاتها',
    section: 'G',
    division: '47',
    class: '47.22',
  },
  {
    code: '47.23',
    nameEn: 'Retail sale of fish, crustaceans and molluscs in specialized stores',
    nameAr: 'البيع بالتجزئة للأسماك والقشريات',
    section: 'G',
    division: '47',
    class: '47.23',
  },
  {
    code: '47.24',
    nameEn: 'Retail sale of bread, cakes, flour confectionery and sugar confectionery',
    nameAr: 'البيع بالتجزئة للخبز والمعجنات والحلويات',
    section: 'G',
    division: '47',
    class: '47.24',
  },
  {
    code: '47.25',
    nameEn: 'Retail sale of beverages in specialized stores',
    nameAr: 'البيع بالتجزئة للمشروبات',
    section: 'G',
    division: '47',
    class: '47.25',
  },
  {
    code: '47.26',
    nameEn: 'Retail sale of tobacco products in specialized stores',
    nameAr: 'البيع بالتجزئة لمنتجات التبغ',
    section: 'G',
    division: '47',
    class: '47.26',
  },
  {
    code: '47.29',
    nameEn: 'Other retail sale of food in specialized stores',
    nameAr: 'البيع بالتجزئة لأغذية أخرى',
    section: 'G',
    division: '47',
    class: '47.29',
  },
  {
    code: '47.30',
    nameEn: 'Retail sale of automotive fuel in specialized stores',
    nameAr: 'البيع بالتجزئة للوقود',
    section: 'G',
    division: '47',
    class: '47.30',
  },
  {
    code: '47.41',
    nameEn: 'Retail sale of computers, peripheral units and software',
    nameAr: 'البيع بالتجزئة للحواسيب والبرمجيات',
    section: 'G',
    division: '47',
    class: '47.41',
  },
  {
    code: '47.42',
    nameEn: 'Retail sale of telecommunications equipment',
    nameAr: 'البيع بالتجزئة لمعدات الاتصالات',
    section: 'G',
    division: '47',
    class: '47.42',
  },
  {
    code: '47.43',
    nameEn: 'Retail sale of audio and video equipment',
    nameAr: 'البيع بالتجزئة لمعدات الصوت والصورة',
    section: 'G',
    division: '47',
    class: '47.43',
  },
  {
    code: '47.51',
    nameEn: 'Retail sale of textiles in specialized stores',
    nameAr: 'البيع بالتجزئة للمنسوجات',
    section: 'G',
    division: '47',
    class: '47.51',
  },
  {
    code: '47.52',
    nameEn: 'Retail sale of hardware, paints and glass',
    nameAr: 'البيع بالتجزئة للأدوات والدهانات والزجاج',
    section: 'G',
    division: '47',
    class: '47.52',
  },
  {
    code: '47.53',
    nameEn: 'Retail sale of carpets, rugs, wall and floor coverings',
    nameAr: 'البيع بالتجزئة للسجاد والموكيت',
    section: 'G',
    division: '47',
    class: '47.53',
  },
  {
    code: '47.54',
    nameEn: 'Retail sale of electrical household appliances',
    nameAr: 'البيع بالتجزئة للأجهزة الكهربائية المنزلية',
    section: 'G',
    division: '47',
    class: '47.54',
  },
  {
    code: '47.59',
    nameEn: 'Retail sale of furniture, lighting equipment and household articles n.e.c.',
    nameAr: 'البيع بالتجزئة للأثاث والإضاءة',
    section: 'G',
    division: '47',
    class: '47.59',
  },
  {
    code: '47.61',
    nameEn: 'Retail sale of books in specialized stores',
    nameAr: 'البيع بالتجزئة للكتب',
    section: 'G',
    division: '47',
    class: '47.61',
  },
  {
    code: '47.62',
    nameEn: 'Retail sale of newspapers and stationery',
    nameAr: 'البيع بالتجزئة للصحف والقرطاسية',
    section: 'G',
    division: '47',
    class: '47.62',
  },
  {
    code: '47.63',
    nameEn: 'Retail sale of music and video recordings',
    nameAr: 'البيع بالتجزئة للتسجيلات الموسيقية',
    section: 'G',
    division: '47',
    class: '47.63',
  },
  {
    code: '47.64',
    nameEn: 'Retail sale of sporting equipment',
    nameAr: 'البيع بالتجزئة للمعدات الرياضية',
    section: 'G',
    division: '47',
    class: '47.64',
  },
  {
    code: '47.65',
    nameEn: 'Retail sale of games and toys',
    nameAr: 'البيع بالتجزئة للألعاب',
    section: 'G',
    division: '47',
    class: '47.65',
  },
  {
    code: '47.71',
    nameEn: 'Retail sale of clothing in specialized stores',
    nameAr: 'البيع بالتجزئة للملابس',
    section: 'G',
    division: '47',
    class: '47.71',
  },
  {
    code: '47.72',
    nameEn: 'Retail sale of footwear and leather goods',
    nameAr: 'البيع بالتجزئة للأحذية والمنتجات الجلدية',
    section: 'G',
    division: '47',
    class: '47.72',
  },
  {
    code: '47.73',
    nameEn: 'Dispensing chemist in specialized stores',
    nameAr: 'البيع بالتجزئة للأدوية (صيدليات)',
    section: 'G',
    division: '47',
    class: '47.73',
  },
  {
    code: '47.74',
    nameEn: 'Retail sale of medical and orthopaedic goods',
    nameAr: 'البيع بالتجزئة للمستلزمات الطبية',
    section: 'G',
    division: '47',
    class: '47.74',
  },
  {
    code: '47.75',
    nameEn: 'Retail sale of cosmetic and toilet articles',
    nameAr: 'البيع بالتجزئة لمستحضرات التجميل',
    section: 'G',
    division: '47',
    class: '47.75',
  },
  {
    code: '47.76',
    nameEn: 'Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food',
    nameAr: 'البيع بالتجزئة للزهور والنباتات',
    section: 'G',
    division: '47',
    class: '47.76',
  },
  {
    code: '47.77',
    nameEn: 'Retail sale of watches and jewellery',
    nameAr: 'البيع بالتجزئة للساعات والمجوهرات',
    section: 'G',
    division: '47',
    class: '47.77',
  },
  {
    code: '47.78',
    nameEn: 'Other retail sale of new goods in specialized stores',
    nameAr: 'البيع بالتجزئة لسلع جديدة أخرى',
    section: 'G',
    division: '47',
    class: '47.78',
  },
  {
    code: '47.79',
    nameEn: 'Retail sale of second-hand goods',
    nameAr: 'البيع بالتجزئة للسلع المستعملة',
    section: 'G',
    division: '47',
    class: '47.79',
  },
  {
    code: '47.91',
    nameEn: 'Retail sale via mail order houses or via Internet',
    nameAr: 'البيع بالتجزئة عبر البريد أو الإنترنت',
    section: 'G',
    division: '47',
    class: '47.91',
  },
  {
    code: '47.99',
    nameEn: 'Other retail sale not in stores, stalls or markets',
    nameAr: 'البيع بالتجزئة خارج المحلات',
    section: 'G',
    division: '47',
    class: '47.99',
  },
  
  // ============================================
  // SECTION I: ACCOMMODATION AND FOOD SERVICE
  // ============================================
  
  {
    code: '55.10',
    nameEn: 'Short-term accommodation activities',
    nameAr: 'أنشطة الإقامة قصيرة الأجل',
    section: 'I',
    division: '55',
    class: '55.10',
  },
  {
    code: '55.20',
    nameEn: 'Camping grounds, recreational vehicle parks and trailer parks',
    nameAr: 'المخيمات ومواقف العربات السكنية',
    section: 'I',
    division: '55',
    class: '55.20',
  },
  {
    code: '55.90',
    nameEn: 'Other accommodation',
    nameAr: 'أنشطة إقامة أخرى',
    section: 'I',
    division: '55',
    class: '55.90',
  },
  {
    code: '56.10',
    nameEn: 'Restaurants and mobile food service activities',
    nameAr: 'المطاعم وخدمات الطعام المتنقلة',
    section: 'I',
    division: '56',
    class: '56.10',
  },
  {
    code: '56.21',
    nameEn: 'Event catering',
    nameAr: 'خدمات تقديم الطعام للمناسبات',
    section: 'I',
    division: '56',
    class: '56.21',
  },
  {
    code: '56.29',
    nameEn: 'Other food service activities',
    nameAr: 'أنشطة خدمات الطعام الأخرى',
    section: 'I',
    division: '56',
    class: '56.29',
  },
  {
    code: '56.30',
    nameEn: 'Beverage serving activities',
    nameAr: 'أنشطة تقديم المشروبات',
    section: 'I',
    division: '56',
    class: '56.30',
  },
  
  // ============================================
  // SECTION J: INFORMATION AND COMMUNICATION
  // ============================================
  
  {
    code: '58.11',
    nameEn: 'Book publishing',
    nameAr: 'نشر الكتب',
    section: 'J',
    division: '58',
    class: '58.11',
  },
  {
    code: '58.12',
    nameEn: 'Publishing of directories and mailing lists',
    nameAr: 'نشر الأدلة وقوائم المراسلات',
    section: 'J',
    division: '58',
    class: '58.12',
  },
  {
    code: '58.13',
    nameEn: 'Publishing of newspapers, journals and periodicals',
    nameAr: 'نشر الصحف والمجلات والدوريات',
    section: 'J',
    division: '58',
    class: '58.13',
  },
  {
    code: '58.14',
    nameEn: 'Publishing of journals and periodicals',
    nameAr: 'نشر المجلات والدوريات',
    section: 'J',
    division: '58',
    class: '58.14',
  },
  {
    code: '58.19',
    nameEn: 'Other publishing activities',
    nameAr: 'أنشطة النشر الأخرى',
    section: 'J',
    division: '58',
    class: '58.19',
  },
  {
    code: '58.21',
    nameEn: 'Publishing of computer games',
    nameAr: 'نشر ألعاب الحاسوب',
    section: 'J',
    division: '58',
    class: '58.21',
  },
  {
    code: '58.29',
    nameEn: 'Other software publishing',
    nameAr: 'نشر برمجيات أخرى',
    section: 'J',
    division: '58',
    class: '58.29',
  },
  {
    code: '59.11',
    nameEn: 'Motion picture, video and television programme production activities',
    nameAr: 'إنتاج الأفلام والفيديو والبرامج التلفزيونية',
    section: 'J',
    division: '59',
    class: '59.11',
  },
  {
    code: '59.12',
    nameEn: 'Motion picture, video and television programme post-production activities',
    nameAr: 'أنشطة ما بعد إنتاج الأفلام والفيديو',
    section: 'J',
    division: '59',
    class: '59.12',
  },
  {
    code: '59.13',
    nameEn: 'Motion picture, video and television programme distribution activities',
    nameAr: 'توزيع الأفلام والفيديو والبرامج التلفزيونية',
    section: 'J',
    division: '59',
    class: '59.13',
  },
  {
    code: '59.14',
    nameEn: 'Motion picture projection activities',
    nameAr: 'عرض الأفلام السينمائية',
    section: 'J',
    division: '59',
    class: '59.14',
  },
  {
    code: '59.20',
    nameEn: 'Sound recording and music publishing activities',
    nameAr: 'التسجيل الصوتي ونشر الموسيقى',
    section: 'J',
    division: '59',
    class: '59.20',
  },
  {
    code: '60.10',
    nameEn: 'Radio broadcasting',
    nameAr: 'البث الإذاعي',
    section: 'J',
    division: '60',
    class: '60.10',
  },
  {
    code: '60.20',
    nameEn: 'Television programming and broadcasting activities',
    nameAr: 'البرمجة والبث التلفزيوني',
    section: 'J',
    division: '60',
    class: '60.20',
  },
  {
    code: '61.10',
    nameEn: 'Wired telecommunications activities',
    nameAr: 'أنشطة الاتصالات السلكية',
    section: 'J',
    division: '61',
    class: '61.10',
  },
  {
    code: '61.20',
    nameEn: 'Wireless telecommunications activities',
    nameAr: 'أنشطة الاتصالات اللاسلكية',
    section: 'J',
    division: '61',
    class: '61.20',
  },
  {
    code: '61.30',
    nameEn: 'Satellite telecommunications activities',
    nameAr: 'أنشطة الاتصالات عبر الأقمار الصناعية',
    section: 'J',
    division: '61',
    class: '61.30',
  },
  {
    code: '61.90',
    nameEn: 'Other telecommunications activities',
    nameAr: 'أنشطة اتصالات أخرى',
    section: 'J',
    division: '61',
    class: '61.90',
  },
  {
    code: '62.01',
    nameEn: 'Computer programming activities',
    nameAr: 'أنشطة برمجة الحاسوب',
    section: 'J',
    division: '62',
    class: '62.01',
  },
  {
    code: '62.02',
    nameEn: 'Computer consultancy and computer facilities management activities',
    nameAr: 'الاستشارات الحاسوبية وإدارة المرافق',
    section: 'J',
    division: '62',
    class: '62.02',
  },
  {
    code: '62.03',
    nameEn: 'Computer facilities management activities',
    nameAr: 'إدارة المرافق الحاسوبية',
    section: 'J',
    division: '62',
    class: '62.03',
  },
  {
    code: '62.09',
    nameEn: 'Other information technology and computer service activities',
    nameAr: 'أنشطة تقنية المعلومات والحاسوب الأخرى',
    section: 'J',
    division: '62',
    class: '62.09',
  },
  {
    code: '63.11',
    nameEn: 'Data processing, hosting and related activities',
    nameAr: 'معالجة البيانات والاستضافة',
    section: 'J',
    division: '63',
    class: '63.11',
  },
  {
    code: '63.12',
    nameEn: 'Web portals',
    nameAr: 'بوابات الويب',
    section: 'J',
    division: '63',
    class: '63.12',
  },
  {
    code: '63.91',
    nameEn: 'News agency activities',
    nameAr: 'أنشطة وكالات الأنباء',
    section: 'J',
    division: '63',
    class: '63.91',
  },
  {
    code: '63.99',
    nameEn: 'Other information service activities n.e.c.',
    nameAr: 'أنشطة خدمات المعلومات الأخرى',
    section: 'J',
    division: '63',
    class: '63.99',
  },
  
  // ============================================
  // SECTION K: FINANCIAL AND INSURANCE ACTIVITIES
  // ============================================
  
  {
    code: '64.11',
    nameEn: 'Central banking',
    nameAr: 'الخدمات المصرفية المركزية',
    section: 'K',
    division: '64',
    class: '64.11',
  },
  {
    code: '64.19',
    nameEn: 'Other monetary intermediation',
    nameAr: 'الوساطة المالية الأخرى',
    section: 'K',
    division: '64',
    class: '64.19',
  },
  {
    code: '64.20',
    nameEn: 'Activities of holding companies',
    nameAr: 'أنشطة الشركات القابضة',
    section: 'K',
    division: '64',
    class: '64.20',
  },
  {
    code: '64.30',
    nameEn: 'Trusts, funds and similar financial entities',
    nameAr: 'الصناديق الاستثمارية والكيانات المالية المماثلة',
    section: 'K',
    division: '64',
    class: '64.30',
  },
  {
    code: '64.91',
    nameEn: 'Financial leasing',
    nameAr: 'التأجير التمويلي',
    section: 'K',
    division: '64',
    class: '64.91',
  },
  {
    code: '64.92',
    nameEn: 'Other credit granting',
    nameAr: 'منح الائتمان الآخر',
    section: 'K',
    division: '64',
    class: '64.92',
  },
  {
    code: '64.99',
    nameEn: 'Other financial service activities, except insurance and pension funding n.e.c.',
    nameAr: 'أنشطة الخدمات المالية الأخرى',
    section: 'K',
    division: '64',
    class: '64.99',
  },
  {
    code: '65.11',
    nameEn: 'Life insurance',
    nameAr: 'التأمين على الحياة',
    section: 'K',
    division: '65',
    class: '65.11',
  },
  {
    code: '65.12',
    nameEn: 'Non-life insurance',
    nameAr: 'التأمين العام',
    section: 'K',
    division: '65',
    class: '65.12',
  },
  {
    code: '65.20',
    nameEn: 'Reinsurance',
    nameAr: 'إعادة التأمين',
    section: 'K',
    division: '65',
    class: '65.20',
  },
  {
    code: '65.30',
    nameEn: 'Pension funding',
    nameAr: 'صناديق التقاعد',
    section: 'K',
    division: '65',
    class: '65.30',
  },
  {
    code: '66.11',
    nameEn: 'Administration of financial markets',
    nameAr: 'إدارة الأسواق المالية',
    section: 'K',
    division: '66',
    class: '66.11',
  },
  {
    code: '66.12',
    nameEn: 'Security and commodity contracts brokerage',
    nameAr: 'الوساطة في الأوراق المالية والسلع',
    section: 'K',
    division: '66',
    class: '66.12',
  },
  {
    code: '66.19',
    nameEn: 'Other activities auxiliary to financial service activities',
    nameAr: 'أنشطة مساعدة أخرى للخدمات المالية',
    section: 'K',
    division: '66',
    class: '66.19',
  },
  {
    code: '66.21',
    nameEn: 'Risk and damage evaluation',
    nameAr: 'تقييم المخاطر والأضرار',
    section: 'K',
    division: '66',
    class: '66.21',
  },
  {
    code: '66.22',
    nameEn: 'Activities of insurance agents and brokers',
    nameAr: 'أنشطة وكلاء ووسطاء التأمين',
    section: 'K',
    division: '66',
    class: '66.22',
  },
  {
    code: '66.29',
    nameEn: 'Other activities auxiliary to insurance and pension funding',
    nameAr: 'أنشطة مساعدة أخرى للتأمين',
    section: 'K',
    division: '66',
    class: '66.29',
  },
  {
    code: '66.30',
    nameEn: 'Fund management activities',
    nameAr: 'أنشطة إدارة الصناديق',
    section: 'K',
    division: '66',
    class: '66.30',
  },
  
  // ============================================
  // SECTION M: PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES
  // ============================================
  
  {
    code: '69.10',
    nameEn: 'Legal activities',
    nameAr: 'الأنشطة القانونية',
    section: 'M',
    division: '69',
    class: '69.10',
  },
  {
    code: '69.20',
    nameEn: 'Accounting, bookkeeping and auditing activities; tax consultancy',
    nameAr: 'أنشطة المحاسبة والمراجعة والاستشارات الضريبية',
    section: 'M',
    division: '69',
    class: '69.20',
  },
  {
    code: '70.10',
    nameEn: 'Activities of head offices',
    nameAr: 'أنشطة المكاتب الرئيسية',
    section: 'M',
    division: '70',
    class: '70.10',
  },
  {
    code: '70.21',
    nameEn: 'Public relations and communication activities',
    nameAr: 'أنشطة العلاقات العامة والاتصالات',
    section: 'M',
    division: '70',
    class: '70.21',
  },
  {
    code: '70.22',
    nameEn: 'Business and other management consultancy activities',
    nameAr: 'أنشطة الاستشارات الإدارية والتجارية',
    section: 'M',
    division: '70',
    class: '70.22',
  },
  {
    code: '71.11',
    nameEn: 'Architectural activities',
    nameAr: 'الأنشطة الهندسية المعمارية',
    section: 'M',
    division: '71',
    class: '71.11',
  },
  {
    code: '71.12',
    nameEn: 'Engineering activities and related technical consultancy',
    nameAr: 'الأنشطة الهندسية والاستشارات التقنية',
    section: 'M',
    division: '71',
    class: '71.12',
  },
  {
    code: '71.20',
    nameEn: 'Technical testing and analysis',
    nameAr: 'الاختبارات والتحليلات التقنية',
    section: 'M',
    division: '71',
    class: '71.20',
  },
  {
    code: '72.11',
    nameEn: 'Research and experimental development on biotechnology',
    nameAr: 'البحث والتطوير في التكنولوجيا الحيوية',
    section: 'M',
    division: '72',
    class: '72.11',
  },
  {
    code: '72.19',
    nameEn: 'Other research and experimental development on natural sciences and engineering',
    nameAr: 'البحث والتطوير الآخر في العلوم الطبيعية',
    section: 'M',
    division: '72',
    class: '72.19',
  },
  {
    code: '72.20',
    nameEn: 'Research and experimental development on social sciences and humanities',
    nameAr: 'البحث والتطوير في العلوم الاجتماعية',
    section: 'M',
    division: '72',
    class: '72.20',
  },
  {
    code: '73.11',
    nameEn: 'Advertising agencies',
    nameAr: 'وكالات الإعلان',
    section: 'M',
    division: '73',
    class: '73.11',
  },
  {
    code: '73.12',
    nameEn: 'Media representation',
    nameAr: 'التمثيل الإعلامي',
    section: 'M',
    division: '73',
    class: '73.12',
  },
  {
    code: '73.20',
    nameEn: 'Market research and public opinion polling',
    nameAr: 'بحوث السوق واستطلاع الرأي',
    section: 'M',
    division: '73',
    class: '73.20',
  },
  {
    code: '74.10',
    nameEn: 'Specialized design activities',
    nameAr: 'أنشطة التصميم المتخصصة',
    section: 'M',
    division: '74',
    class: '74.10',
  },
  {
    code: '74.20',
    nameEn: 'Photographic activities',
    nameAr: 'أنشطة التصوير الفوتوغرافي',
    section: 'M',
    division: '74',
    class: '74.20',
  },
  {
    code: '74.30',
    nameEn: 'Translation and interpretation activities',
    nameAr: 'أنشطة الترجمة والترجمة الفورية',
    section: 'M',
    division: '74',
    class: '74.30',
  },
  {
    code: '74.90',
    nameEn: 'Other professional, scientific and technical activities n.e.c.',
    nameAr: 'أنشطة مهنية وعلمية وتقنية أخرى',
    section: 'M',
    division: '74',
    class: '74.90',
  },
  {
    code: '75.00',
    nameEn: 'Veterinary activities',
    nameAr: 'الأنشطة البيطرية',
    section: 'M',
    division: '75',
    class: '75.00',
  },
  
  // ============================================
  // SECTION P: EDUCATION
  // ============================================
  
  {
    code: '85.10',
    nameEn: 'Pre-primary education',
    nameAr: 'التعليم قبل الابتدائي',
    section: 'P',
    division: '85',
    class: '85.10',
  },
  {
    code: '85.20',
    nameEn: 'Primary education',
    nameAr: 'التعليم الابتدائي',
    section: 'P',
    division: '85',
    class: '85.20',
  },
  {
    code: '85.31',
    nameEn: 'General secondary education',
    nameAr: 'التعليم الثانوي العام',
    section: 'P',
    division: '85',
    class: '85.31',
  },
  {
    code: '85.32',
    nameEn: 'Technical and vocational secondary education',
    nameAr: 'التعليم الثانوي التقني والمهني',
    section: 'P',
    division: '85',
    class: '85.32',
  },
  {
    code: '85.41',
    nameEn: 'Post-secondary non-tertiary education',
    nameAr: 'التعليم ما بعد الثانوي غير العالي',
    section: 'P',
    division: '85',
    class: '85.41',
  },
  {
    code: '85.42',
    nameEn: 'Tertiary education',
    nameAr: 'التعليم العالي',
    section: 'P',
    division: '85',
    class: '85.42',
  },
  {
    code: '85.51',
    nameEn: 'Sports and recreation education',
    nameAr: 'التعليم الرياضي والترفيهي',
    section: 'P',
    division: '85',
    class: '85.51',
  },
  {
    code: '85.52',
    nameEn: 'Cultural education',
    nameAr: 'التعليم الثقافي',
    section: 'P',
    division: '85',
    class: '85.52',
  },
  {
    code: '85.53',
    nameEn: 'Driving school activities',
    nameAr: 'أنشطة مدارس تعليم القيادة',
    section: 'P',
    division: '85',
    class: '85.53',
  },
  {
    code: '85.59',
    nameEn: 'Other education n.e.c.',
    nameAr: 'أنشطة تعليمية أخرى',
    section: 'P',
    division: '85',
    class: '85.59',
  },
  {
    code: '85.60',
    nameEn: 'Educational support activities',
    nameAr: 'أنشطة الدعم التعليمي',
    section: 'P',
    division: '85',
    class: '85.60',
  },
  
  // ============================================
  // SECTION Q: HUMAN HEALTH AND SOCIAL WORK
  // ============================================
  
  {
    code: '86.10',
    nameEn: 'Hospital activities',
    nameAr: 'أنشطة المستشفيات',
    section: 'Q',
    division: '86',
    class: '86.10',
  },
  {
    code: '86.21',
    nameEn: 'General medical practice activities',
    nameAr: 'أنشطة الممارسة الطبية العامة',
    section: 'Q',
    division: '86',
    class: '86.21',
  },
  {
    code: '86.22',
    nameEn: 'Specialist medical practice activities',
    nameAr: 'أنشطة الممارسة الطبية المتخصصة',
    section: 'Q',
    division: '86',
    class: '86.22',
  },
  {
    code: '86.23',
    nameEn: 'Dental practice activities',
    nameAr: 'أنشطة طب الأسنان',
    section: 'Q',
    division: '86',
    class: '86.23',
  },
  {
    code: '86.90',
    nameEn: 'Other human health activities',
    nameAr: 'أنشطة الصحة البشرية الأخرى',
    section: 'Q',
    division: '86',
    class: '86.90',
  },
  {
    code: '87.10',
    nameEn: 'Residential nursing care facilities',
    nameAr: 'مرافق الرعاية التمريضية السكنية',
    section: 'Q',
    division: '87',
    class: '87.10',
  },
  {
    code: '87.20',
    nameEn: 'Residential care activities for mental retardation, mental health and substance abuse',
    nameAr: 'أنشطة الرعاية السكنية للصحة العقلية',
    section: 'Q',
    division: '87',
    class: '87.20',
  },
  {
    code: '87.30',
    nameEn: 'Residential care activities for the elderly and disabled',
    nameAr: 'أنشطة الرعاية السكنية لكبار السن وذوي الإعاقة',
    section: 'Q',
    division: '87',
    class: '87.30',
  },
  {
    code: '87.90',
    nameEn: 'Other residential care activities',
    nameAr: 'أنشطة الرعاية السكنية الأخرى',
    section: 'Q',
    division: '87',
    class: '87.90',
  },
  {
    code: '88.10',
    nameEn: 'Social work activities without accommodation for the elderly and disabled',
    nameAr: 'أنشطة الخدمة الاجتماعية لكبار السن وذوي الإعاقة',
    section: 'Q',
    division: '88',
    class: '88.10',
  },
  {
    code: '88.91',
    nameEn: 'Child day-care activities',
    nameAr: 'أنشطة رعاية الأطفال النهارية',
    section: 'Q',
    division: '88',
    class: '88.91',
  },
  {
    code: '88.99',
    nameEn: 'Other social work activities without accommodation n.e.c.',
    nameAr: 'أنشطة الخدمة الاجتماعية الأخرى بدون إقامة',
    section: 'Q',
    division: '88',
    class: '88.99',
  },
  
  // ============================================
  // SECTION R: ARTS, ENTERTAINMENT AND RECREATION
  // ============================================
  
  {
    code: '90.01',
    nameEn: 'Performing arts',
    nameAr: 'الفنون الأدائية',
    section: 'R',
    division: '90',
    class: '90.01',
  },
  {
    code: '90.02',
    nameEn: 'Support activities to performing arts',
    nameAr: 'أنشطة الدعم للفنون الأدائية',
    section: 'R',
    division: '90',
    class: '90.02',
  },
  {
    code: '90.03',
    nameEn: 'Artistic creation',
    nameAr: 'الإبداع الفني',
    section: 'R',
    division: '90',
    class: '90.03',
  },
  {
    code: '90.04',
    nameEn: 'Operation of arts facilities',
    nameAr: 'تشغيل المرافق الفنية',
    section: 'R',
    division: '90',
    class: '90.04',
  },
  {
    code: '91.01',
    nameEn: 'Library and archives activities',
    nameAr: 'أنشطة المكتبات والأرشيفات',
    section: 'R',
    division: '91',
    class: '91.01',
  },
  {
    code: '91.02',
    nameEn: 'Museums activities and operation of historical sites and buildings',
    nameAr: 'أنشطة المتاحف والمواقع التاريخية',
    section: 'R',
    division: '91',
    class: '91.02',
  },
  {
    code: '91.03',
    nameEn: 'Botanical and zoological gardens and nature reserves activities',
    nameAr: 'أنشطة الحدائق النباتية وحدائق الحيوان',
    section: 'R',
    division: '91',
    class: '91.03',
  },
  {
    code: '92.00',
    nameEn: 'Gambling and betting activities',
    nameAr: 'أنشطة القمار والمراهنة',
    section: 'R',
    division: '92',
    class: '92.00',
  },
  {
    code: '93.11',
    nameEn: 'Operation of sports facilities',
    nameAr: 'تشغيل المرافق الرياضية',
    section: 'R',
    division: '93',
    class: '93.11',
  },
  {
    code: '93.12',
    nameEn: 'Activities of sports clubs',
    nameAr: 'أنشطة النوادي الرياضية',
    section: 'R',
    division: '93',
    class: '93.12',
  },
  {
    code: '93.13',
    nameEn: 'Fitness facilities',
    nameAr: 'مراكز اللياقة البدنية',
    section: 'R',
    division: '93',
    class: '93.13',
  },
  {
    code: '93.19',
    nameEn: 'Other sports activities',
    nameAr: 'أنشطة رياضية أخرى',
    section: 'R',
    division: '93',
    class: '93.19',
  },
  {
    code: '93.21',
    nameEn: 'Activities of amusement parks and theme parks',
    nameAr: 'أنشطة مدن الملاهي والمتنزهات الترفيهية',
    section: 'R',
    division: '93',
    class: '93.21',
  },
  {
    code: '93.29',
    nameEn: 'Other amusement and recreation activities',
    nameAr: 'أنشطة الترفيه والتسلية الأخرى',
    section: 'R',
    division: '93',
    class: '93.29',
  },
  
  // ============================================
  // SECTION S: OTHER SERVICE ACTIVITIES
  // ============================================
  
  {
    code: '94.11',
    nameEn: 'Activities of business and employers membership organizations',
    nameAr: 'أنشطة منظمات الأعمال وأصحاب العمل',
    section: 'S',
    division: '94',
    class: '94.11',
  },
  {
    code: '94.12',
    nameEn: 'Activities of professional membership organizations',
    nameAr: 'أنشطة المنظمات المهنية',
    section: 'S',
    division: '94',
    class: '94.12',
  },
  {
    code: '94.20',
    nameEn: 'Activities of trade unions',
    nameAr: 'أنشطة النقابات العمالية',
    section: 'S',
    division: '94',
    class: '94.20',
  },
  {
    code: '94.91',
    nameEn: 'Activities of religious organizations',
    nameAr: 'أنشطة المنظمات الدينية',
    section: 'S',
    division: '94',
    class: '94.91',
  },
  {
    code: '94.92',
    nameEn: 'Activities of political organizations',
    nameAr: 'أنشطة المنظمات السياسية',
    section: 'S',
    division: '94',
    class: '94.92',
  },
  {
    code: '94.99',
    nameEn: 'Activities of other membership organizations n.e.c.',
    nameAr: 'أنشطة المنظمات العضوية الأخرى',
    section: 'S',
    division: '94',
    class: '94.99',
  },
  {
    code: '95.11',
    nameEn: 'Repair of computers and peripheral equipment',
    nameAr: 'إصلاح الحواسيب والمعدات الطرفية',
    section: 'S',
    division: '95',
    class: '95.11',
  },
  {
    code: '95.12',
    nameEn: 'Repair of communication equipment',
    nameAr: 'إصلاح معدات الاتصالات',
    section: 'S',
    division: '95',
    class: '95.12',
  },
  {
    code: '95.21',
    nameEn: 'Repair of consumer electronics',
    nameAr: 'إصلاح الإلكترونيات الاستهلاكية',
    section: 'S',
    division: '95',
    class: '95.21',
  },
  {
    code: '95.22',
    nameEn: 'Repair of household appliances and home and garden equipment',
    nameAr: 'إصلاح الأجهزة المنزلية ومعدات المنزل والحديقة',
    section: 'S',
    division: '95',
    class: '95.22',
  },
  {
    code: '95.23',
    nameEn: 'Repair of footwear and leather goods',
    nameAr: 'إصلاح الأحذية والمنتجات الجلدية',
    section: 'S',
    division: '95',
    class: '95.23',
  },
  {
    code: '95.24',
    nameEn: 'Repair of furniture and home furnishings',
    nameAr: 'إصلاح الأثاث والمفروشات المنزلية',
    section: 'S',
    division: '95',
    class: '95.24',
  },
  {
    code: '95.25',
    nameEn: 'Repair of watches, clocks and jewellery',
    nameAr: 'إصلاح الساعات والمجوهرات',
    section: 'S',
    division: '95',
    class: '95.25',
  },
  {
    code: '95.29',
    nameEn: 'Repair of other personal and household goods',
    nameAr: 'إصلاح السلع الشخصية والمنزلية الأخرى',
    section: 'S',
    division: '95',
    class: '95.29',
  },
  {
    code: '96.01',
    nameEn: 'Washing and (dry-)cleaning of textile and fur products',
    nameAr: 'غسل وتنظيف المنسوجات والفراء',
    section: 'S',
    division: '96',
    class: '96.01',
  },
  {
    code: '96.02',
    nameEn: 'Hairdressing and other beauty treatment',
    nameAr: 'تصفيف الشعر ومعالجات التجميل الأخرى',
    section: 'S',
    division: '96',
    class: '96.02',
  },
  {
    code: '96.03',
    nameEn: 'Funeral and related activities',
    nameAr: 'أنشطة الجنازات وما يتصل بها',
    section: 'S',
    division: '96',
    class: '96.03',
  },
  {
    code: '96.04',
    nameEn: 'Physical well-being activities',
    nameAr: 'أنشطة الرفاه البدني',
    section: 'S',
    division: '96',
    class: '96.04',
  },
  {
    code: '96.09',
    nameEn: 'Other personal service activities n.e.c.',
    nameAr: 'أنشطة الخدمات الشخصية الأخرى',
    section: 'S',
    division: '96',
    class: '96.09',
  },
];

// Helper functions
export const getActivitiesBySection = (sectionCode: string): BusinessActivity[] => {
  return businessActivities.filter(activity => activity.section === sectionCode);
};

export const getActivitiesByDivision = (divisionCode: string): BusinessActivity[] => {
  return businessActivities.filter(activity => activity.division === divisionCode);
};

export const searchActivities = (searchTerm: string): BusinessActivity[] => {
  const term = searchTerm.toLowerCase();
  return businessActivities.filter(
    activity =>
      activity.code.toLowerCase().includes(term) ||
      activity.nameEn.toLowerCase().includes(term) ||
      activity.nameAr.includes(term)
  );
};

export const getSectionByCode = (code: string): BusinessSection | undefined => {
  return isicSections.find(section => section.code === code);
};
