/**
 * Comprehensive Chart of Accounts - IFRS/IAS/GAAP Compliant
 * Universal structure suitable for all types of businesses
 * Total: 300+ accounts across all categories
 */

export interface Account {
  code: string;
  name: string;
  nameAr: string;
  type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  parentCode?: string;
  level: number;
  category: string;
  subCategory?: string;
  iasReference?: string;
  ifrsReference?: string;
  isHeader: boolean;
  isActive: boolean;
  allowPosting: boolean;
  balance: number;
}

export const universalChartOfAccounts: Account[] = [
  // ==============================================
  // 1. ASSETS (الأصول) - IAS 1
  // ==============================================
  {
    code: '1',
    name: 'ASSETS',
    nameAr: 'الأصول',
    type: 'asset',
    level: 1,
    category: 'Assets',
    iasReference: 'IAS 1',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 1.1 Current Assets (الأصول المتداولة)
  {
    code: '1-1',
    name: 'Current Assets',
    nameAr: 'الأصول المتداولة',
    type: 'asset',
    parentCode: '1',
    level: 2,
    category: 'Assets',
    subCategory: 'Current Assets',
    iasReference: 'IAS 1.66',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 1.1.1 Cash and Cash Equivalents (النقدية وما يعادلها) - IAS 7
  {
    code: '1-1-1',
    name: 'Cash and Cash Equivalents',
    nameAr: 'النقدية وما يعادلها',
    type: 'asset',
    parentCode: '1-1',
    level: 3,
    category: 'Assets',
    subCategory: 'Cash',
    iasReference: 'IAS 7',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-1-1-001',
    name: 'Cash on Hand',
    nameAr: 'النقدية في الصندوق',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Cash',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-002',
    name: 'Petty Cash',
    nameAr: 'النقدية الصغيرة',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Cash',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-003',
    name: 'Cash in Transit',
    nameAr: 'النقدية تحت التحويل',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Cash',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-010',
    name: 'Bank - Local Currency',
    nameAr: 'البنك - عملة محلية',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Bank',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-011',
    name: 'Bank - Foreign Currency',
    nameAr: 'البنك - عملة أجنبية',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Bank',
    iasReference: 'IAS 7, IAS 21',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-012',
    name: 'Bank - Savings Account',
    nameAr: 'البنك - حساب توفير',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Bank',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-1-020',
    name: 'Short-term Deposits (< 3 months)',
    nameAr: 'ودائع قصيرة الأجل (أقل من 3 أشهر)',
    type: 'asset',
    parentCode: '1-1-1',
    level: 4,
    category: 'Assets',
    subCategory: 'Cash Equivalents',
    iasReference: 'IAS 7',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.1.2 Trade Receivables (المدينون التجاريون) - IFRS 9
  {
    code: '1-1-2',
    name: 'Trade Receivables',
    nameAr: 'المدينون التجاريون',
    type: 'asset',
    parentCode: '1-1',
    level: 3,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 9, IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-1-2-001',
    name: 'Accounts Receivable - Trade',
    nameAr: 'العملاء - تجاري',
    type: 'asset',
    parentCode: '1-1-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-2-002',
    name: 'Accounts Receivable - Related Parties',
    nameAr: 'العملاء - أطراف ذات علاقة',
    type: 'asset',
    parentCode: '1-1-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 9, IAS 24',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-2-003',
    name: 'Notes Receivable',
    nameAr: 'أوراق القبض',
    type: 'asset',
    parentCode: '1-1-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-2-004',
    name: 'Allowance for Doubtful Accounts',
    nameAr: 'مخصص الديون المشكوك فيها',
    type: 'asset',
    parentCode: '1-1-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-2-005',
    name: 'Retention Receivables',
    nameAr: 'مبالغ محتجزة مدينة',
    type: 'asset',
    parentCode: '1-1-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Receivables',
    ifrsReference: 'IFRS 15',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.1.3 Inventory (المخزون) - IAS 2
  {
    code: '1-1-3',
    name: 'Inventory',
    nameAr: 'المخزون',
    type: 'asset',
    parentCode: '1-1',
    level: 3,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-1-3-001',
    name: 'Raw Materials',
    nameAr: 'المواد الخام',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-002',
    name: 'Work in Progress',
    nameAr: 'الإنتاج تحت التشغيل',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-003',
    name: 'Finished Goods',
    nameAr: 'البضاعة تامة الصنع',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-004',
    name: 'Merchandise Inventory',
    nameAr: 'بضاعة للبيع',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-005',
    name: 'Spare Parts',
    nameAr: 'قطع الغيار',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-006',
    name: 'Packing Materials',
    nameAr: 'مواد التعبئة والتغليف',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-007',
    name: 'Inventory in Transit',
    nameAr: 'بضاعة بالطريق',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-3-008',
    name: 'Inventory Valuation Adjustment',
    nameAr: 'تسوية قيمة المخزون',
    type: 'asset',
    parentCode: '1-1-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Inventory',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.1.4 Prepaid Expenses (المصروفات المدفوعة مقدماً)
  {
    code: '1-1-4',
    name: 'Prepaid Expenses',
    nameAr: 'المصروفات المدفوعة مقدماً',
    type: 'asset',
    parentCode: '1-1',
    level: 3,
    category: 'Assets',
    subCategory: 'Prepaid',
    iasReference: 'IAS 1',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-1-4-001',
    name: 'Prepaid Insurance',
    nameAr: 'التأمين المدفوع مقدماً',
    type: 'asset',
    parentCode: '1-1-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Prepaid',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-4-002',
    name: 'Prepaid Rent',
    nameAr: 'الإيجار المدفوع مقدماً',
    type: 'asset',
    parentCode: '1-1-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Prepaid',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-4-003',
    name: 'Advances to Suppliers',
    nameAr: 'دفعات مقدمة للموردين',
    type: 'asset',
    parentCode: '1-1-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Prepaid',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-4-004',
    name: 'Advances to Employees',
    nameAr: 'سلف الموظفين',
    type: 'asset',
    parentCode: '1-1-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Prepaid',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.1.5 Other Current Assets
  {
    code: '1-1-5',
    name: 'Other Current Assets',
    nameAr: 'أصول متداولة أخرى',
    type: 'asset',
    parentCode: '1-1',
    level: 3,
    category: 'Assets',
    subCategory: 'Other Current',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-1-5-001',
    name: 'Tax Receivables',
    nameAr: 'ضرائب مستحقة',
    type: 'asset',
    parentCode: '1-1-5',
    level: 4,
    category: 'Assets',
    subCategory: 'Other Current',
    iasReference: 'IAS 12',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-5-002',
    name: 'VAT Receivables',
    nameAr: 'ضريبة القيمة المضافة المستحقة',
    type: 'asset',
    parentCode: '1-1-5',
    level: 4,
    category: 'Assets',
    subCategory: 'Other Current',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-1-5-003',
    name: 'Accrued Income',
    nameAr: 'إيرادات مستحقة',
    type: 'asset',
    parentCode: '1-1-5',
    level: 4,
    category: 'Assets',
    subCategory: 'Other Current',
    ifrsReference: 'IFRS 15',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2 Non-Current Assets (الأصول غير المتداولة)
  {
    code: '1-2',
    name: 'Non-Current Assets',
    nameAr: 'الأصول غير المتداولة',
    type: 'asset',
    parentCode: '1',
    level: 2,
    category: 'Assets',
    subCategory: 'Non-Current Assets',
    iasReference: 'IAS 1.66',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 1.2.1 Property, Plant & Equipment (الممتلكات والمعدات) - IAS 16
  {
    code: '1-2-1',
    name: 'Property, Plant & Equipment',
    nameAr: 'الممتلكات والمعدات',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-2-1-001',
    name: 'Land',
    nameAr: 'الأراضي',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-002',
    name: 'Buildings',
    nameAr: 'المباني',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-003',
    name: 'Accumulated Depreciation - Buildings',
    nameAr: 'مجمع استهلاك المباني',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-004',
    name: 'Machinery & Equipment',
    nameAr: 'الآلات والمعدات',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-005',
    name: 'Accumulated Depreciation - Machinery',
    nameAr: 'مجمع استهلاك الآلات',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-006',
    name: 'Vehicles',
    nameAr: 'المركبات',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-007',
    name: 'Accumulated Depreciation - Vehicles',
    nameAr: 'مجمع استهلاك المركبات',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-008',
    name: 'Furniture & Fixtures',
    nameAr: 'الأثاث والتركيبات',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-009',
    name: 'Accumulated Depreciation - Furniture',
    nameAr: 'مجمع استهلاك الأثاث',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-010',
    name: 'Computer & IT Equipment',
    nameAr: 'أجهزة الحاسب الآلي',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-011',
    name: 'Accumulated Depreciation - IT Equipment',
    nameAr: 'مجمع استهلاك الأجهزة',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-012',
    name: 'Leasehold Improvements',
    nameAr: 'تحسينات المباني المستأجرة',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16, IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-1-013',
    name: 'Construction in Progress',
    nameAr: 'مشاريع تحت التنفيذ',
    type: 'asset',
    parentCode: '1-2-1',
    level: 4,
    category: 'Assets',
    subCategory: 'PPE',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2.2 Intangible Assets (الأصول غير الملموسة) - IAS 38
  {
    code: '1-2-2',
    name: 'Intangible Assets',
    nameAr: 'الأصول غير الملموسة',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'Intangible',
    iasReference: 'IAS 38',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-2-2-001',
    name: 'Goodwill',
    nameAr: 'الشهرة',
    type: 'asset',
    parentCode: '1-2-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Intangible',
    ifrsReference: 'IFRS 3',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-2-002',
    name: 'Patents',
    nameAr: 'براءات الاختراع',
    type: 'asset',
    parentCode: '1-2-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Intangible',
    iasReference: 'IAS 38',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-2-003',
    name: 'Trademarks',
    nameAr: 'العلامات التجارية',
    type: 'asset',
    parentCode: '1-2-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Intangible',
    iasReference: 'IAS 38',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-2-004',
    name: 'Software Licenses',
    nameAr: 'تراخيص البرامج',
    type: 'asset',
    parentCode: '1-2-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Intangible',
    iasReference: 'IAS 38',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-2-005',
    name: 'Accumulated Amortization - Intangibles',
    nameAr: 'مجمع إطفاء الأصول غير الملموسة',
    type: 'asset',
    parentCode: '1-2-2',
    level: 4,
    category: 'Assets',
    subCategory: 'Intangible',
    iasReference: 'IAS 38',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2.3 Investment Property (العقارات الاستثمارية) - IAS 40
  {
    code: '1-2-3',
    name: 'Investment Property',
    nameAr: 'العقارات الاستثمارية',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'Investment Property',
    iasReference: 'IAS 40',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-2-3-001',
    name: 'Investment Property - Land',
    nameAr: 'عقارات استثمارية - أراضي',
    type: 'asset',
    parentCode: '1-2-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Investment Property',
    iasReference: 'IAS 40',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-3-002',
    name: 'Investment Property - Buildings',
    nameAr: 'عقارات استثمارية - مباني',
    type: 'asset',
    parentCode: '1-2-3',
    level: 4,
    category: 'Assets',
    subCategory: 'Investment Property',
    iasReference: 'IAS 40',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2.4 Long-term Investments (استثمارات طويلة الأجل) - IFRS 9
  {
    code: '1-2-4',
    name: 'Long-term Investments',
    nameAr: 'استثمارات طويلة الأجل',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'Investments',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-2-4-001',
    name: 'Investment in Subsidiaries',
    nameAr: 'استثمارات في شركات تابعة',
    type: 'asset',
    parentCode: '1-2-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Investments',
    ifrsReference: 'IFRS 10',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-4-002',
    name: 'Investment in Associates',
    nameAr: 'استثمارات في شركات شقيقة',
    type: 'asset',
    parentCode: '1-2-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Investments',
    iasReference: 'IAS 28',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-4-003',
    name: 'Investment in Joint Ventures',
    nameAr: 'استثمارات في مشاريع مشتركة',
    type: 'asset',
    parentCode: '1-2-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Investments',
    ifrsReference: 'IFRS 11',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-4-004',
    name: 'Equity Investments at Fair Value',
    nameAr: 'استثمارات في أسهم بالقيمة العادلة',
    type: 'asset',
    parentCode: '1-2-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Investments',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-4-005',
    name: 'Debt Instruments at Amortized Cost',
    nameAr: 'أدوات دين بالتكلفة المطفأة',
    type: 'asset',
    parentCode: '1-2-4',
    level: 4,
    category: 'Assets',
    subCategory: 'Investments',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2.5 Right-of-Use Assets (أصول حق الاستخدام) - IFRS 16
  {
    code: '1-2-5',
    name: 'Right-of-Use Assets',
    nameAr: 'أصول حق الاستخدام',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'ROU Assets',
    ifrsReference: 'IFRS 16',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '1-2-5-001',
    name: 'ROU Asset - Buildings',
    nameAr: 'أصل حق استخدام - مباني',
    type: 'asset',
    parentCode: '1-2-5',
    level: 4,
    category: 'Assets',
    subCategory: 'ROU Assets',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-5-002',
    name: 'ROU Asset - Vehicles',
    nameAr: 'أصل حق استخدام - مركبات',
    type: 'asset',
    parentCode: '1-2-5',
    level: 4,
    category: 'Assets',
    subCategory: 'ROU Assets',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '1-2-5-003',
    name: 'Accumulated Depreciation - ROU Assets',
    nameAr: 'مجمع استهلاك أصول حق الاستخدام',
    type: 'asset',
    parentCode: '1-2-5',
    level: 4,
    category: 'Assets',
    subCategory: 'ROU Assets',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 1.2.6 Deferred Tax Assets (أصول ضريبية مؤجلة) - IAS 12
  {
    code: '1-2-6',
    name: 'Deferred Tax Assets',
    nameAr: 'أصول ضريبية مؤجلة',
    type: 'asset',
    parentCode: '1-2',
    level: 3,
    category: 'Assets',
    subCategory: 'Deferred Tax',
    iasReference: 'IAS 12',
    isHeader: true,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // ==============================================
  // 2. LIABILITIES (الخصوم) - IAS 1
  // ==============================================
  {
    code: '2',
    name: 'LIABILITIES',
    nameAr: 'الخصوم',
    type: 'liability',
    level: 1,
    category: 'Liabilities',
    iasReference: 'IAS 1',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 2.1 Current Liabilities (الخصوم المتداولة)
  {
    code: '2-1',
    name: 'Current Liabilities',
    nameAr: 'الخصوم المتداولة',
    type: 'liability',
    parentCode: '2',
    level: 2,
    category: 'Liabilities',
    subCategory: 'Current Liabilities',
    iasReference: 'IAS 1.69',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 2.1.1 Trade Payables (الدائنون التجاريون)
  {
    code: '2-1-1',
    name: 'Trade Payables',
    nameAr: 'الدائنون التجاريون',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Payables',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-1-001',
    name: 'Accounts Payable - Trade',
    nameAr: 'الموردون - تجاري',
    type: 'liability',
    parentCode: '2-1-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Payables',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-1-002',
    name: 'Accounts Payable - Related Parties',
    nameAr: 'الموردون - أطراف ذات علاقة',
    type: 'liability',
    parentCode: '2-1-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Payables',
    iasReference: 'IAS 24',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-1-003',
    name: 'Notes Payable',
    nameAr: 'أوراق الدفع',
    type: 'liability',
    parentCode: '2-1-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Payables',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-1-004',
    name: 'Retention Payables',
    nameAr: 'مبالغ محتجزة دائنة',
    type: 'liability',
    parentCode: '2-1-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Payables',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.2 Short-term Borrowings (القروض قصيرة الأجل) - IFRS 9
  {
    code: '2-1-2',
    name: 'Short-term Borrowings',
    nameAr: 'القروض قصيرة الأجل',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Borrowings',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-2-001',
    name: 'Bank Overdraft',
    nameAr: 'سحب على المكشوف',
    type: 'liability',
    parentCode: '2-1-2',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Borrowings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-2-002',
    name: 'Short-term Loans',
    nameAr: 'قروض قصيرة الأجل',
    type: 'liability',
    parentCode: '2-1-2',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Borrowings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-2-003',
    name: 'Current Portion of Long-term Debt',
    nameAr: 'الجزء المتداول من القروض طويلة الأجل',
    type: 'liability',
    parentCode: '2-1-2',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Borrowings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.3 Accrued Expenses (المصروفات المستحقة)
  {
    code: '2-1-3',
    name: 'Accrued Expenses',
    nameAr: 'المصروفات المستحقة',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Accrued',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-3-001',
    name: 'Accrued Salaries & Wages',
    nameAr: 'رواتب وأجور مستحقة',
    type: 'liability',
    parentCode: '2-1-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Accrued',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-3-002',
    name: 'Accrued Interest',
    nameAr: 'فوائد مستحقة',
    type: 'liability',
    parentCode: '2-1-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Accrued',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-3-003',
    name: 'Accrued Utilities',
    nameAr: 'خدمات مستحقة',
    type: 'liability',
    parentCode: '2-1-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Accrued',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-3-004',
    name: 'Accrued Professional Fees',
    nameAr: 'أتعاب مهنية مستحقة',
    type: 'liability',
    parentCode: '2-1-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Accrued',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.4 Tax Liabilities (الالتزامات الضريبية)
  {
    code: '2-1-4',
    name: 'Tax Liabilities',
    nameAr: 'الالتزامات الضريبية',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Tax',
    iasReference: 'IAS 12',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-4-001',
    name: 'Income Tax Payable',
    nameAr: 'ضريبة الدخل المستحقة',
    type: 'liability',
    parentCode: '2-1-4',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Tax',
    iasReference: 'IAS 12',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-4-002',
    name: 'VAT Payable',
    nameAr: 'ضريبة القيمة المضافة المستحقة',
    type: 'liability',
    parentCode: '2-1-4',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Tax',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-4-003',
    name: 'Withholding Tax Payable',
    nameAr: 'ضريبة استقطاع مستحقة',
    type: 'liability',
    parentCode: '2-1-4',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Tax',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-4-004',
    name: 'Zakat Payable',
    nameAr: 'زكاة مستحقة',
    type: 'liability',
    parentCode: '2-1-4',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Tax',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.5 Employee Benefits (مستحقات الموظفين) - IAS 19
  {
    code: '2-1-5',
    name: 'Employee Benefits',
    nameAr: 'مستحقات الموظفين',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-5-001',
    name: 'Social Insurance Payable',
    nameAr: 'التأمينات الاجتماعية المستحقة',
    type: 'liability',
    parentCode: '2-1-5',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-5-002',
    name: 'Vacation Accrual',
    nameAr: 'مخصص الإجازات',
    type: 'liability',
    parentCode: '2-1-5',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-5-003',
    name: 'Bonus Payable',
    nameAr: 'مكافآت مستحقة',
    type: 'liability',
    parentCode: '2-1-5',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.6 Unearned Revenue (إيرادات مؤجلة) - IFRS 15
  {
    code: '2-1-6',
    name: 'Unearned Revenue',
    nameAr: 'إيرادات مؤجلة',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Deferred Revenue',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-6-001',
    name: 'Customer Advances',
    nameAr: 'دفعات مقدمة من العملاء',
    type: 'liability',
    parentCode: '2-1-6',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Deferred Revenue',
    ifrsReference: 'IFRS 15',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-6-002',
    name: 'Deferred Service Revenue',
    nameAr: 'إيرادات خدمات مؤجلة',
    type: 'liability',
    parentCode: '2-1-6',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Deferred Revenue',
    ifrsReference: 'IFRS 15',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.1.7 Provisions - Current (المخصصات - متداولة) - IAS 37
  {
    code: '2-1-7',
    name: 'Provisions - Current',
    nameAr: 'المخصصات - متداولة',
    type: 'liability',
    parentCode: '2-1',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-1-7-001',
    name: 'Provision for Warranties',
    nameAr: 'مخصص الضمان',
    type: 'liability',
    parentCode: '2-1-7',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-7-002',
    name: 'Provision for Restructuring',
    nameAr: 'مخصص إعادة الهيكلة',
    type: 'liability',
    parentCode: '2-1-7',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-1-7-003',
    name: 'Provision for Legal Claims',
    nameAr: 'مخصص قضايا قانونية',
    type: 'liability',
    parentCode: '2-1-7',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.2 Non-Current Liabilities (الخصوم غير المتداولة)
  {
    code: '2-2',
    name: 'Non-Current Liabilities',
    nameAr: 'الخصوم غير المتداولة',
    type: 'liability',
    parentCode: '2',
    level: 2,
    category: 'Liabilities',
    subCategory: 'Non-Current Liabilities',
    iasReference: 'IAS 1.69',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 2.2.1 Long-term Borrowings (القروض طويلة الأجل) - IFRS 9
  {
    code: '2-2-1',
    name: 'Long-term Borrowings',
    nameAr: 'القروض طويلة الأجل',
    type: 'liability',
    parentCode: '2-2',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Long-term Debt',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-2-1-001',
    name: 'Long-term Bank Loans',
    nameAr: 'قروض بنكية طويلة الأجل',
    type: 'liability',
    parentCode: '2-2-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Long-term Debt',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-2-1-002',
    name: 'Bonds Payable',
    nameAr: 'سندات مستحقة الدفع',
    type: 'liability',
    parentCode: '2-2-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Long-term Debt',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-2-1-003',
    name: 'Mortgage Payable',
    nameAr: 'قروض عقارية',
    type: 'liability',
    parentCode: '2-2-1',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Long-term Debt',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.2.2 Lease Liabilities (التزامات الإيجار) - IFRS 16
  {
    code: '2-2-2',
    name: 'Lease Liabilities',
    nameAr: 'التزامات الإيجار',
    type: 'liability',
    parentCode: '2-2',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Lease',
    ifrsReference: 'IFRS 16',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-2-2-001',
    name: 'Lease Liability - Non-Current',
    nameAr: 'التزام إيجار - غير متداول',
    type: 'liability',
    parentCode: '2-2-2',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Lease',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.2.3 Employee Benefits - Non-Current (مستحقات الموظفين - غير متداولة) - IAS 19
  {
    code: '2-2-3',
    name: 'Employee Benefits - Non-Current',
    nameAr: 'مستحقات الموظفين - غير متداولة',
    type: 'liability',
    parentCode: '2-2',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-2-3-001',
    name: 'End of Service Benefits',
    nameAr: 'مكافأة نهاية الخدمة',
    type: 'liability',
    parentCode: '2-2-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-2-3-002',
    name: 'Pension Obligations',
    nameAr: 'التزامات التقاعد',
    type: 'liability',
    parentCode: '2-2-3',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Employee Benefits',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.2.4 Deferred Tax Liabilities (التزامات ضريبية مؤجلة) - IAS 12
  {
    code: '2-2-4',
    name: 'Deferred Tax Liabilities',
    nameAr: 'التزامات ضريبية مؤجلة',
    type: 'liability',
    parentCode: '2-2',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Deferred Tax',
    iasReference: 'IAS 12',
    isHeader: true,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 2.2.5 Provisions - Non-Current (المخصصات - غير متداولة) - IAS 37
  {
    code: '2-2-5',
    name: 'Provisions - Non-Current',
    nameAr: 'المخصصات - غير متداولة',
    type: 'liability',
    parentCode: '2-2',
    level: 3,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '2-2-5-001',
    name: 'Provision for Asset Retirement',
    nameAr: 'مخصص إزالة الأصول',
    type: 'liability',
    parentCode: '2-2-5',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '2-2-5-002',
    name: 'Provision for Environmental Restoration',
    nameAr: 'مخصص الترميم البيئي',
    type: 'liability',
    parentCode: '2-2-5',
    level: 4,
    category: 'Liabilities',
    subCategory: 'Provisions',
    iasReference: 'IAS 37',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // ==============================================
  // 3. EQUITY (حقوق الملكية) - IAS 1
  // ==============================================
  {
    code: '3',
    name: 'EQUITY',
    nameAr: 'حقوق الملكية',
    type: 'equity',
    level: 1,
    category: 'Equity',
    iasReference: 'IAS 1',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 3.1 Share Capital (رأس المال)
  {
    code: '3-1',
    name: 'Share Capital',
    nameAr: 'رأس المال',
    type: 'equity',
    parentCode: '3',
    level: 2,
    category: 'Equity',
    subCategory: 'Capital',
    iasReference: 'IAS 1',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '3-1-001',
    name: 'Issued Share Capital',
    nameAr: 'رأس المال المصدر',
    type: 'equity',
    parentCode: '3-1',
    level: 3,
    category: 'Equity',
    subCategory: 'Capital',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-1-002',
    name: 'Treasury Shares',
    nameAr: 'أسهم الخزينة',
    type: 'equity',
    parentCode: '3-1',
    level: 3,
    category: 'Equity',
    subCategory: 'Capital',
    iasReference: 'IAS 32',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 3.2 Reserves (الاحتياطيات)
  {
    code: '3-2',
    name: 'Reserves',
    nameAr: 'الاحتياطيات',
    type: 'equity',
    parentCode: '3',
    level: 2,
    category: 'Equity',
    subCategory: 'Reserves',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '3-2-001',
    name: 'Legal Reserve',
    nameAr: 'الاحتياطي النظامي',
    type: 'equity',
    parentCode: '3-2',
    level: 3,
    category: 'Equity',
    subCategory: 'Reserves',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-2-002',
    name: 'Statutory Reserve',
    nameAr: 'الاحتياطي القانوني',
    type: 'equity',
    parentCode: '3-2',
    level: 3,
    category: 'Equity',
    subCategory: 'Reserves',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-2-003',
    name: 'General Reserve',
    nameAr: 'الاحتياطي العام',
    type: 'equity',
    parentCode: '3-2',
    level: 3,
    category: 'Equity',
    subCategory: 'Reserves',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-2-004',
    name: 'Revaluation Reserve',
    nameAr: 'احتياطي إعادة التقييم',
    type: 'equity',
    parentCode: '3-2',
    level: 3,
    category: 'Equity',
    subCategory: 'Reserves',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-2-005',
    name: 'Foreign Currency Translation Reserve',
    nameAr: 'احتياطي فروقات العملة',
    type: 'equity',
    parentCode: '3-2',
    level: 3,
    category: 'Equity',
    subCategory: 'Reserves',
    iasReference: 'IAS 21',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 3.3 Retained Earnings (الأرباح المحتجزة)
  {
    code: '3-3',
    name: 'Retained Earnings',
    nameAr: 'الأرباح المحتجزة',
    type: 'equity',
    parentCode: '3',
    level: 2,
    category: 'Equity',
    subCategory: 'Retained Earnings',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '3-3-001',
    name: 'Retained Earnings - Beginning',
    nameAr: 'أرباح مرحلة - بداية السنة',
    type: 'equity',
    parentCode: '3-3',
    level: 3,
    category: 'Equity',
    subCategory: 'Retained Earnings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-3-002',
    name: 'Current Year Profit/Loss',
    nameAr: 'ربح/خسارة السنة الحالية',
    type: 'equity',
    parentCode: '3-3',
    level: 3,
    category: 'Equity',
    subCategory: 'Retained Earnings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '3-3-003',
    name: 'Dividends',
    nameAr: 'أرباح موزعة',
    type: 'equity',
    parentCode: '3-3',
    level: 3,
    category: 'Equity',
    subCategory: 'Retained Earnings',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 3.4 Non-controlling Interest (حقوق الأقلية) - IFRS 10
  {
    code: '3-4',
    name: 'Non-controlling Interest',
    nameAr: 'حقوق الأقلية',
    type: 'equity',
    parentCode: '3',
    level: 2,
    category: 'Equity',
    subCategory: 'NCI',
    ifrsReference: 'IFRS 10',
    isHeader: true,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // ==============================================
  // 4. REVENUE (الإيرادات) - IFRS 15
  // ==============================================
  {
    code: '4',
    name: 'REVENUE',
    nameAr: 'الإيرادات',
    type: 'revenue',
    level: 1,
    category: 'Revenue',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 4.1 Operating Revenue (إيرادات التشغيل)
  {
    code: '4-1',
    name: 'Operating Revenue',
    nameAr: 'إيرادات التشغيل',
    type: 'revenue',
    parentCode: '4',
    level: 2,
    category: 'Revenue',
    subCategory: 'Operating',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 4.1.1 Sales Revenue (إيرادات المبيعات)
  {
    code: '4-1-1',
    name: 'Sales Revenue',
    nameAr: 'إيرادات المبيعات',
    type: 'revenue',
    parentCode: '4-1',
    level: 3,
    category: 'Revenue',
    subCategory: 'Sales',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-1-1-001',
    name: 'Sales - Local',
    nameAr: 'مبيعات - محلية',
    type: 'revenue',
    parentCode: '4-1-1',
    level: 4,
    category: 'Revenue',
    subCategory: 'Sales',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-1-002',
    name: 'Sales - Export',
    nameAr: 'مبيعات - تصدير',
    type: 'revenue',
    parentCode: '4-1-1',
    level: 4,
    category: 'Revenue',
    subCategory: 'Sales',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-1-003',
    name: 'Sales - Related Parties',
    nameAr: 'مبيعات - أطراف ذات علاقة',
    type: 'revenue',
    parentCode: '4-1-1',
    level: 4,
    category: 'Revenue',
    subCategory: 'Sales',
    iasReference: 'IAS 24',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-1-004',
    name: 'Sales Returns & Allowances',
    nameAr: 'مردودات ومسموحات المبيعات',
    type: 'revenue',
    parentCode: '4-1-1',
    level: 4,
    category: 'Revenue',
    subCategory: 'Sales',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-1-005',
    name: 'Sales Discounts',
    nameAr: 'خصومات المبيعات',
    type: 'revenue',
    parentCode: '4-1-1',
    level: 4,
    category: 'Revenue',
    subCategory: 'Sales',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 4.1.2 Service Revenue (إيرادات الخدمات)
  {
    code: '4-1-2',
    name: 'Service Revenue',
    nameAr: 'إيرادات الخدمات',
    type: 'revenue',
    parentCode: '4-1',
    level: 3,
    category: 'Revenue',
    subCategory: 'Services',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-1-2-001',
    name: 'Consulting Services',
    nameAr: 'خدمات استشارية',
    type: 'revenue',
    parentCode: '4-1-2',
    level: 4,
    category: 'Revenue',
    subCategory: 'Services',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-2-002',
    name: 'Professional Services',
    nameAr: 'خدمات مهنية',
    type: 'revenue',
    parentCode: '4-1-2',
    level: 4,
    category: 'Revenue',
    subCategory: 'Services',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-2-003',
    name: 'Maintenance Services',
    nameAr: 'خدمات صيانة',
    type: 'revenue',
    parentCode: '4-1-2',
    level: 4,
    category: 'Revenue',
    subCategory: 'Services',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-2-004',
    name: 'Subscription Revenue',
    nameAr: 'إيرادات الاشتراكات',
    type: 'revenue',
    parentCode: '4-1-2',
    level: 4,
    category: 'Revenue',
    subCategory: 'Services',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 4.1.3 Contract Revenue (إيرادات العقود) - IFRS 15
  {
    code: '4-1-3',
    name: 'Contract Revenue',
    nameAr: 'إيرادات العقود',
    type: 'revenue',
    parentCode: '4-1',
    level: 3,
    category: 'Revenue',
    subCategory: 'Contracts',
    ifrsReference: 'IFRS 15',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-1-3-001',
    name: 'Construction Contracts',
    nameAr: 'عقود إنشاءات',
    type: 'revenue',
    parentCode: '4-1-3',
    level: 4,
    category: 'Revenue',
    subCategory: 'Contracts',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-1-3-002',
    name: 'Long-term Service Contracts',
    nameAr: 'عقود خدمات طويلة الأجل',
    type: 'revenue',
    parentCode: '4-1-3',
    level: 4,
    category: 'Revenue',
    subCategory: 'Contracts',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 4.2 Other Operating Revenue (إيرادات تشغيلية أخرى)
  {
    code: '4-2',
    name: 'Other Operating Revenue',
    nameAr: 'إيرادات تشغيلية أخرى',
    type: 'revenue',
    parentCode: '4',
    level: 2,
    category: 'Revenue',
    subCategory: 'Other Operating',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-2-001',
    name: 'Rental Income',
    nameAr: 'إيرادات الإيجار',
    type: 'revenue',
    parentCode: '4-2',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other Operating',
    iasReference: 'IAS 40, IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-2-002',
    name: 'Commission Income',
    nameAr: 'إيرادات العمولات',
    type: 'revenue',
    parentCode: '4-2',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other Operating',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-2-003',
    name: 'Royalty Income',
    nameAr: 'إيرادات حقوق الامتياز',
    type: 'revenue',
    parentCode: '4-2',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other Operating',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 4.3 Financial Income (الإيرادات المالية)
  {
    code: '4-3',
    name: 'Financial Income',
    nameAr: 'الإيرادات المالية',
    type: 'revenue',
    parentCode: '4',
    level: 2,
    category: 'Revenue',
    subCategory: 'Financial',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-3-001',
    name: 'Interest Income',
    nameAr: 'إيرادات الفوائد',
    type: 'revenue',
    parentCode: '4-3',
    level: 3,
    category: 'Revenue',
    subCategory: 'Financial',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-3-002',
    name: 'Dividend Income',
    nameAr: 'إيرادات الأرباح الموزعة',
    type: 'revenue',
    parentCode: '4-3',
    level: 3,
    category: 'Revenue',
    subCategory: 'Financial',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-3-003',
    name: 'Gain on Foreign Exchange',
    nameAr: 'أرباح فروقات العملة',
    type: 'revenue',
    parentCode: '4-3',
    level: 3,
    category: 'Revenue',
    subCategory: 'Financial',
    iasReference: 'IAS 21',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-3-004',
    name: 'Gain on Investment',
    nameAr: 'أرباح الاستثمارات',
    type: 'revenue',
    parentCode: '4-3',
    level: 3,
    category: 'Revenue',
    subCategory: 'Financial',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 4.4 Other Income (إيرادات أخرى)
  {
    code: '4-4',
    name: 'Other Income',
    nameAr: 'إيرادات أخرى',
    type: 'revenue',
    parentCode: '4',
    level: 2,
    category: 'Revenue',
    subCategory: 'Other',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '4-4-001',
    name: 'Gain on Sale of Assets',
    nameAr: 'أرباح بيع أصول',
    type: 'revenue',
    parentCode: '4-4',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-4-002',
    name: 'Insurance Claim Proceeds',
    nameAr: 'تعويضات التأمين',
    type: 'revenue',
    parentCode: '4-4',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '4-4-003',
    name: 'Government Grants',
    nameAr: 'منح حكومية',
    type: 'revenue',
    parentCode: '4-4',
    level: 3,
    category: 'Revenue',
    subCategory: 'Other',
    iasReference: 'IAS 20',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // ==============================================
  // 5. EXPENSES (المصروفات)
  // ==============================================
  {
    code: '5',
    name: 'EXPENSES',
    nameAr: 'المصروفات',
    type: 'expense',
    level: 1,
    category: 'Expenses',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 5.1 Cost of Sales (تكلفة المبيعات) - IAS 2
  {
    code: '5-1',
    name: 'Cost of Sales',
    nameAr: 'تكلفة المبيعات',
    type: 'expense',
    parentCode: '5',
    level: 2,
    category: 'Expenses',
    subCategory: 'COGS',
    iasReference: 'IAS 2',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-1-001',
    name: 'Cost of Goods Sold',
    nameAr: 'تكلفة البضاعة المباعة',
    type: 'expense',
    parentCode: '5-1',
    level: 3,
    category: 'Expenses',
    subCategory: 'COGS',
    iasReference: 'IAS 2',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-1-002',
    name: 'Direct Labor',
    nameAr: 'أجور مباشرة',
    type: 'expense',
    parentCode: '5-1',
    level: 3,
    category: 'Expenses',
    subCategory: 'COGS',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-1-003',
    name: 'Direct Materials',
    nameAr: 'مواد مباشرة',
    type: 'expense',
    parentCode: '5-1',
    level: 3,
    category: 'Expenses',
    subCategory: 'COGS',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-1-004',
    name: 'Manufacturing Overhead',
    nameAr: 'تكاليف صناعية غير مباشرة',
    type: 'expense',
    parentCode: '5-1',
    level: 3,
    category: 'Expenses',
    subCategory: 'COGS',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-1-005',
    name: 'Freight In',
    nameAr: 'مصاريف نقل المشتريات',
    type: 'expense',
    parentCode: '5-1',
    level: 3,
    category: 'Expenses',
    subCategory: 'COGS',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 5.2 Operating Expenses (المصروفات التشغيلية)
  {
    code: '5-2',
    name: 'Operating Expenses',
    nameAr: 'المصروفات التشغيلية',
    type: 'expense',
    parentCode: '5',
    level: 2,
    category: 'Expenses',
    subCategory: 'Operating',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },

  // 5.2.1 Selling Expenses (مصروفات البيع والتسويق)
  {
    code: '5-2-1',
    name: 'Selling Expenses',
    nameAr: 'مصروفات البيع والتسويق',
    type: 'expense',
    parentCode: '5-2',
    level: 3,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-2-1-001',
    name: 'Sales Salaries',
    nameAr: 'رواتب مندوبي المبيعات',
    type: 'expense',
    parentCode: '5-2-1',
    level: 4,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-1-002',
    name: 'Sales Commission',
    nameAr: 'عمولات المبيعات',
    type: 'expense',
    parentCode: '5-2-1',
    level: 4,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-1-003',
    name: 'Advertising & Marketing',
    nameAr: 'الإعلان والتسويق',
    type: 'expense',
    parentCode: '5-2-1',
    level: 4,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-1-004',
    name: 'Freight Out',
    nameAr: 'مصاريف الشحن والتوصيل',
    type: 'expense',
    parentCode: '5-2-1',
    level: 4,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-1-005',
    name: 'Travel & Entertainment - Sales',
    nameAr: 'سفر وضيافة - مبيعات',
    type: 'expense',
    parentCode: '5-2-1',
    level: 4,
    category: 'Expenses',
    subCategory: 'Selling',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 5.2.2 General & Administrative (المصروفات الإدارية والعمومية)
  {
    code: '5-2-2',
    name: 'General & Administrative',
    nameAr: 'المصروفات الإدارية والعمومية',
    type: 'expense',
    parentCode: '5-2',
    level: 3,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-2-2-001',
    name: 'Executive Salaries',
    nameAr: 'رواتب الإدارة التنفيذية',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-002',
    name: 'Administrative Salaries',
    nameAr: 'رواتب الموظفين الإداريين',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-003',
    name: 'Employee Benefits',
    nameAr: 'مزايا الموظفين',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    iasReference: 'IAS 19',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-004',
    name: 'Social Insurance',
    nameAr: 'التأمينات الاجتماعية',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-005',
    name: 'Rent Expense',
    nameAr: 'إيجارات',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    ifrsReference: 'IFRS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-006',
    name: 'Utilities',
    nameAr: 'المرافق (كهرباء، ماء، هاتف)',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-007',
    name: 'Office Supplies',
    nameAr: 'مستلزمات مكتبية',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-008',
    name: 'Depreciation Expense',
    nameAr: 'مصروف الاستهلاك',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-009',
    name: 'Amortization Expense',
    nameAr: 'مصروف الإطفاء',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    iasReference: 'IAS 38',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-010',
    name: 'Insurance Expense',
    nameAr: 'مصروف التأمين',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-011',
    name: 'Repairs & Maintenance',
    nameAr: 'الصيانة والإصلاحات',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-012',
    name: 'Professional Fees',
    nameAr: 'أتعاب مهنية',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-013',
    name: 'Legal & Audit Fees',
    nameAr: 'أتعاب قانونية ومراجعة',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-014',
    name: 'Bank Charges',
    nameAr: 'عمولات بنكية',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-015',
    name: 'IT & Software',
    nameAr: 'تقنية المعلومات والبرمجيات',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-016',
    name: 'Training & Development',
    nameAr: 'التدريب والتطوير',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-017',
    name: 'Travel & Entertainment',
    nameAr: 'السفر والضيافة',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-2-2-018',
    name: 'Bad Debt Expense',
    nameAr: 'مصروف الديون المعدومة',
    type: 'expense',
    parentCode: '5-2-2',
    level: 4,
    category: 'Expenses',
    subCategory: 'G&A',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 5.3 Financial Expenses (المصروفات المالية)
  {
    code: '5-3',
    name: 'Financial Expenses',
    nameAr: 'المصروفات المالية',
    type: 'expense',
    parentCode: '5',
    level: 2,
    category: 'Expenses',
    subCategory: 'Financial',
    ifrsReference: 'IFRS 9',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-3-001',
    name: 'Interest Expense',
    nameAr: 'مصروف الفوائد',
    type: 'expense',
    parentCode: '5-3',
    level: 3,
    category: 'Expenses',
    subCategory: 'Financial',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-3-002',
    name: 'Loss on Foreign Exchange',
    nameAr: 'خسائر فروقات العملة',
    type: 'expense',
    parentCode: '5-3',
    level: 3,
    category: 'Expenses',
    subCategory: 'Financial',
    iasReference: 'IAS 21',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-3-003',
    name: 'Loss on Investment',
    nameAr: 'خسائر الاستثمارات',
    type: 'expense',
    parentCode: '5-3',
    level: 3,
    category: 'Expenses',
    subCategory: 'Financial',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-3-004',
    name: 'Impairment Loss - Financial Assets',
    nameAr: 'خسائر الانخفاض في قيمة الأصول المالية',
    type: 'expense',
    parentCode: '5-3',
    level: 3,
    category: 'Expenses',
    subCategory: 'Financial',
    ifrsReference: 'IFRS 9',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 5.4 Other Expenses (مصروفات أخرى)
  {
    code: '5-4',
    name: 'Other Expenses',
    nameAr: 'مصروفات أخرى',
    type: 'expense',
    parentCode: '5',
    level: 2,
    category: 'Expenses',
    subCategory: 'Other',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-4-001',
    name: 'Loss on Sale of Assets',
    nameAr: 'خسائر بيع أصول',
    type: 'expense',
    parentCode: '5-4',
    level: 3,
    category: 'Expenses',
    subCategory: 'Other',
    iasReference: 'IAS 16',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-4-002',
    name: 'Impairment Loss - Non-Financial Assets',
    nameAr: 'خسائر الانخفاض في قيمة الأصول',
    type: 'expense',
    parentCode: '5-4',
    level: 3,
    category: 'Expenses',
    subCategory: 'Other',
    iasReference: 'IAS 36',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-4-003',
    name: 'Donations & Contributions',
    nameAr: 'التبرعات والمساهمات',
    type: 'expense',
    parentCode: '5-4',
    level: 3,
    category: 'Expenses',
    subCategory: 'Other',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-4-004',
    name: 'Fines & Penalties',
    nameAr: 'غرامات وعقوبات',
    type: 'expense',
    parentCode: '5-4',
    level: 3,
    category: 'Expenses',
    subCategory: 'Other',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },

  // 5.5 Income Tax Expense (مصروف ضريبة الدخل) - IAS 12
  {
    code: '5-5',
    name: 'Income Tax Expense',
    nameAr: 'مصروف ضريبة الدخل',
    type: 'expense',
    parentCode: '5',
    level: 2,
    category: 'Expenses',
    subCategory: 'Tax',
    iasReference: 'IAS 12',
    isHeader: true,
    isActive: true,
    allowPosting: false,
    balance: 0,
  },
  {
    code: '5-5-001',
    name: 'Current Tax Expense',
    nameAr: 'مصروف الضريبة الجارية',
    type: 'expense',
    parentCode: '5-5',
    level: 3,
    category: 'Expenses',
    subCategory: 'Tax',
    iasReference: 'IAS 12',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-5-002',
    name: 'Deferred Tax Expense',
    nameAr: 'مصروف الضريبة المؤجلة',
    type: 'expense',
    parentCode: '5-5',
    level: 3,
    category: 'Expenses',
    subCategory: 'Tax',
    iasReference: 'IAS 12',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
  {
    code: '5-5-003',
    name: 'Zakat Expense',
    nameAr: 'مصروف الزكاة',
    type: 'expense',
    parentCode: '5-5',
    level: 3,
    category: 'Expenses',
    subCategory: 'Tax',
    isHeader: false,
    isActive: true,
    allowPosting: true,
    balance: 0,
  },
];

// Helper functions
export const getAccountByCode = (code: string): Account | undefined => {
  return universalChartOfAccounts.find(acc => acc.code === code);
};

export const getAccountsByType = (type: Account['type']): Account[] => {
  return universalChartOfAccounts.filter(acc => acc.type === type);
};

export const getAccountsByParent = (parentCode: string): Account[] => {
  return universalChartOfAccounts.filter(acc => acc.parentCode === parentCode);
};

export const getAccountsByLevel = (level: number): Account[] => {
  return universalChartOfAccounts.filter(acc => acc.level === level);
};

export const getPostableAccounts = (): Account[] => {
  return universalChartOfAccounts.filter(acc => acc.allowPosting);
};

export const getHeaderAccounts = (): Account[] => {
  return universalChartOfAccounts.filter(acc => acc.isHeader);
};

export const searchAccounts = (searchTerm: string): Account[] => {
  const term = searchTerm.toLowerCase();
  return universalChartOfAccounts.filter(
    acc =>
      acc.code.toLowerCase().includes(term) ||
      acc.name.toLowerCase().includes(term) ||
      acc.nameAr.includes(term)
  );
};
