export interface Currency {
  code: string;
  nameEn: string;
  nameAr: string;
  symbol: string;
  symbolNative: string;
  decimalDigits: number;
  rounding: number;
  countryCode: string;
  countryNameEn: string;
  countryNameAr: string;
  isActive: boolean;
  isBaseCurrency?: boolean;
}

export interface ExchangeRate {
  id: string;
  fromCurrency: string;
  toCurrency: string;
  rate: number;
  inverseRate: number;
  effectiveDate: string;
  expiryDate?: string;
  source: string;
  isActive: boolean;
  lastUpdated: string;
}

// Comprehensive global currencies list
export const globalCurrencies: Currency[] = [
  // Middle East
  {
    code: 'SAR',
    nameEn: 'Saudi Riyal',
    nameAr: 'ريال سعودي',
    symbol: 'SAR',
    symbolNative: 'ر.س',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SA',
    countryNameEn: 'Saudi Arabia',
    countryNameAr: 'المملكة العربية السعودية',
    isActive: true,
    isBaseCurrency: true,
  },
  {
    code: 'AED',
    nameEn: 'UAE Dirham',
    nameAr: 'درهم إماراتي',
    symbol: 'AED',
    symbolNative: 'د.إ',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AE',
    countryNameEn: 'United Arab Emirates',
    countryNameAr: 'الإمارات العربية المتحدة',
    isActive: true,
  },
  {
    code: 'KWD',
    nameEn: 'Kuwaiti Dinar',
    nameAr: 'دينار كويتي',
    symbol: 'KWD',
    symbolNative: 'د.ك',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'KW',
    countryNameEn: 'Kuwait',
    countryNameAr: 'الكويت',
    isActive: true,
  },
  {
    code: 'BHD',
    nameEn: 'Bahraini Dinar',
    nameAr: 'دينار بحريني',
    symbol: 'BHD',
    symbolNative: 'د.ب',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'BH',
    countryNameEn: 'Bahrain',
    countryNameAr: 'البحرين',
    isActive: true,
  },
  {
    code: 'OMR',
    nameEn: 'Omani Rial',
    nameAr: 'ريال عماني',
    symbol: 'OMR',
    symbolNative: 'ر.ع',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'OM',
    countryNameEn: 'Oman',
    countryNameAr: 'عمان',
    isActive: true,
  },
  {
    code: 'QAR',
    nameEn: 'Qatari Riyal',
    nameAr: 'ريال قطري',
    symbol: 'QAR',
    symbolNative: 'ر.ق',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'QA',
    countryNameEn: 'Qatar',
    countryNameAr: 'قطر',
    isActive: true,
  },
  {
    code: 'JOD',
    nameEn: 'Jordanian Dinar',
    nameAr: 'دينار أردني',
    symbol: 'JOD',
    symbolNative: 'د.ا',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'JO',
    countryNameEn: 'Jordan',
    countryNameAr: 'الأردن',
    isActive: true,
  },
  {
    code: 'EGP',
    nameEn: 'Egyptian Pound',
    nameAr: 'جنيه مصري',
    symbol: 'EGP',
    symbolNative: 'ج.م',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'EG',
    countryNameEn: 'Egypt',
    countryNameAr: 'مصر',
    isActive: true,
  },
  {
    code: 'LBP',
    nameEn: 'Lebanese Pound',
    nameAr: 'ليرة لبنانية',
    symbol: 'LBP',
    symbolNative: 'ل.ل',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'LB',
    countryNameEn: 'Lebanon',
    countryNameAr: 'لبنان',
    isActive: true,
  },
  {
    code: 'SYP',
    nameEn: 'Syrian Pound',
    nameAr: 'ليرة سورية',
    symbol: 'SYP',
    symbolNative: 'ل.س',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SY',
    countryNameEn: 'Syria',
    countryNameAr: 'سوريا',
    isActive: true,
  },
  {
    code: 'IQD',
    nameEn: 'Iraqi Dinar',
    nameAr: 'دينار عراقي',
    symbol: 'IQD',
    symbolNative: 'د.ع',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'IQ',
    countryNameEn: 'Iraq',
    countryNameAr: 'العراق',
    isActive: true,
  },
  {
    code: 'MAD',
    nameEn: 'Moroccan Dirham',
    nameAr: 'درهم مغربي',
    symbol: 'MAD',
    symbolNative: 'د.م',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MA',
    countryNameEn: 'Morocco',
    countryNameAr: 'المغرب',
    isActive: true,
  },
  {
    code: 'TND',
    nameEn: 'Tunisian Dinar',
    nameAr: 'دينار تونسي',
    symbol: 'TND',
    symbolNative: 'د.ت',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'TN',
    countryNameEn: 'Tunisia',
    countryNameAr: 'تونس',
    isActive: true,
  },
  {
    code: 'LYD',
    nameEn: 'Libyan Dinar',
    nameAr: 'دينار ليبي',
    symbol: 'LYD',
    symbolNative: 'د.ل',
    decimalDigits: 3,
    rounding: 0,
    countryCode: 'LY',
    countryNameEn: 'Libya',
    countryNameAr: 'ليبيا',
    isActive: true,
  },
  {
    code: 'DZD',
    nameEn: 'Algerian Dinar',
    nameAr: 'دينار جزائري',
    symbol: 'DZD',
    symbolNative: 'د.ج',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'DZ',
    countryNameEn: 'Algeria',
    countryNameAr: 'الجزائر',
    isActive: true,
  },
  {
    code: 'SDG',
    nameEn: 'Sudanese Pound',
    nameAr: 'جنيه سوداني',
    symbol: 'SDG',
    symbolNative: 'ج.س',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SD',
    countryNameEn: 'Sudan',
    countryNameAr: 'السودان',
    isActive: true,
  },
  {
    code: 'YER',
    nameEn: 'Yemeni Rial',
    nameAr: 'ريال يمني',
    symbol: 'YER',
    symbolNative: 'ر.ي',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'YE',
    countryNameEn: 'Yemen',
    countryNameAr: 'اليمن',
    isActive: true,
  },

  // Major World Currencies
  {
    code: 'USD',
    nameEn: 'US Dollar',
    nameAr: 'دولار أمريكي',
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'US',
    countryNameEn: 'United States',
    countryNameAr: 'الولايات المتحدة',
    isActive: true,
  },
  {
    code: 'EUR',
    nameEn: 'Euro',
    nameAr: 'يورو',
    symbol: '€',
    symbolNative: '€',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'EU',
    countryNameEn: 'European Union',
    countryNameAr: 'الاتحاد الأوروبي',
    isActive: true,
  },
  {
    code: 'GBP',
    nameEn: 'British Pound',
    nameAr: 'جنيه استرليني',
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'GB',
    countryNameEn: 'United Kingdom',
    countryNameAr: 'المملكة المتحدة',
    isActive: true,
  },
  {
    code: 'JPY',
    nameEn: 'Japanese Yen',
    nameAr: 'ين ياباني',
    symbol: '¥',
    symbolNative: '¥',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'JP',
    countryNameEn: 'Japan',
    countryNameAr: 'اليابان',
    isActive: true,
  },
  {
    code: 'CHF',
    nameEn: 'Swiss Franc',
    nameAr: 'فرنك سويسري',
    symbol: 'CHF',
    symbolNative: 'CHF',
    decimalDigits: 2,
    rounding: 0.05,
    countryCode: 'CH',
    countryNameEn: 'Switzerland',
    countryNameAr: 'سويسرا',
    isActive: true,
  },
  {
    code: 'CNY',
    nameEn: 'Chinese Yuan',
    nameAr: 'يوان صيني',
    symbol: 'CN¥',
    symbolNative: '¥',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'CN',
    countryNameEn: 'China',
    countryNameAr: 'الصين',
    isActive: true,
  },
  {
    code: 'INR',
    nameEn: 'Indian Rupee',
    nameAr: 'روبية هندية',
    symbol: '₹',
    symbolNative: '₹',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'IN',
    countryNameEn: 'India',
    countryNameAr: 'الهند',
    isActive: true,
  },
  {
    code: 'CAD',
    nameEn: 'Canadian Dollar',
    nameAr: 'دولار كندي',
    symbol: 'CA$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'CA',
    countryNameEn: 'Canada',
    countryNameAr: 'كندا',
    isActive: true,
  },
  {
    code: 'AUD',
    nameEn: 'Australian Dollar',
    nameAr: 'دولار أسترالي',
    symbol: 'AU$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AU',
    countryNameEn: 'Australia',
    countryNameAr: 'أستراليا',
    isActive: true,
  },
  {
    code: 'TRY',
    nameEn: 'Turkish Lira',
    nameAr: 'ليرة تركية',
    symbol: '₺',
    symbolNative: '₺',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TR',
    countryNameEn: 'Turkey',
    countryNameAr: 'تركيا',
    isActive: true,
  },
  {
    code: 'RUB',
    nameEn: 'Russian Ruble',
    nameAr: 'روبل روسي',
    symbol: '₽',
    symbolNative: '₽',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'RU',
    countryNameEn: 'Russia',
    countryNameAr: 'روسيا',
    isActive: true,
  },
  {
    code: 'BRL',
    nameEn: 'Brazilian Real',
    nameAr: 'ريال برازيلي',
    symbol: 'R$',
    symbolNative: 'R$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BR',
    countryNameEn: 'Brazil',
    countryNameAr: 'البرازيل',
    isActive: true,
  },
  {
    code: 'MXN',
    nameEn: 'Mexican Peso',
    nameAr: 'بيزو مكسيكي',
    symbol: 'MX$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MX',
    countryNameEn: 'Mexico',
    countryNameAr: 'المكسيك',
    isActive: true,
  },
  {
    code: 'ZAR',
    nameEn: 'South African Rand',
    nameAr: 'راند جنوب أفريقي',
    symbol: 'R',
    symbolNative: 'R',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'ZA',
    countryNameEn: 'South Africa',
    countryNameAr: 'جنوب أفريقيا',
    isActive: true,
  },
  {
    code: 'KRW',
    nameEn: 'South Korean Won',
    nameAr: 'وون كوري',
    symbol: '₩',
    symbolNative: '₩',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'KR',
    countryNameEn: 'South Korea',
    countryNameAr: 'كوريا الجنوبية',
    isActive: true,
  },
  {
    code: 'SGD',
    nameEn: 'Singapore Dollar',
    nameAr: 'دولار سنغافوري',
    symbol: 'S$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SG',
    countryNameEn: 'Singapore',
    countryNameAr: 'سنغافورة',
    isActive: true,
  },
  {
    code: 'MYR',
    nameEn: 'Malaysian Ringgit',
    nameAr: 'رينغيت ماليزي',
    symbol: 'RM',
    symbolNative: 'RM',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MY',
    countryNameEn: 'Malaysia',
    countryNameAr: 'ماليزيا',
    isActive: true,
  },
  {
    code: 'IDR',
    nameEn: 'Indonesian Rupiah',
    nameAr: 'روبية إندونيسية',
    symbol: 'Rp',
    symbolNative: 'Rp',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'ID',
    countryNameEn: 'Indonesia',
    countryNameAr: 'إندونيسيا',
    isActive: true,
  },
  {
    code: 'THB',
    nameEn: 'Thai Baht',
    nameAr: 'بات تايلاندي',
    symbol: '฿',
    symbolNative: '฿',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TH',
    countryNameEn: 'Thailand',
    countryNameAr: 'تايلاند',
    isActive: true,
  },
  {
    code: 'PKR',
    nameEn: 'Pakistani Rupee',
    nameAr: 'روبية باكستانية',
    symbol: '₨',
    symbolNative: '₨',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PK',
    countryNameEn: 'Pakistan',
    countryNameAr: 'باكستان',
    isActive: true,
  },
  {
    code: 'BDT',
    nameEn: 'Bangladeshi Taka',
    nameAr: 'تاكا بنغلاديشية',
    symbol: '৳',
    symbolNative: '৳',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BD',
    countryNameEn: 'Bangladesh',
    countryNameAr: 'بنغلاديش',
    isActive: true,
  },
  
  // Additional Middle East & North Africa
  {
    code: 'MRU',
    nameEn: 'Mauritanian Ouguiya',
    nameAr: 'أوقية موريتانية',
    symbol: 'UM',
    symbolNative: 'أ.م',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MR',
    countryNameEn: 'Mauritania',
    countryNameAr: 'موريتانيا',
    isActive: true,
  },
  {
    code: 'DJF',
    nameEn: 'Djiboutian Franc',
    nameAr: 'فرنك جيبوتي',
    symbol: 'Fdj',
    symbolNative: 'ف.ج',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'DJ',
    countryNameEn: 'Djibouti',
    countryNameAr: 'جيبوتي',
    isActive: true,
  },
  {
    code: 'SOS',
    nameEn: 'Somali Shilling',
    nameAr: 'شلن صومالي',
    symbol: 'Sh.So.',
    symbolNative: 'ش.ص',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SO',
    countryNameEn: 'Somalia',
    countryNameAr: 'الصومال',
    isActive: true,
  },
  {
    code: 'KMF',
    nameEn: 'Comoros Franc',
    nameAr: 'فرنك قمري',
    symbol: 'CF',
    symbolNative: 'ف.ق',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'KM',
    countryNameEn: 'Comoros',
    countryNameAr: 'جزر القمر',
    isActive: true,
  },

  // Additional African Currencies
  {
    code: 'NGN',
    nameEn: 'Nigerian Naira',
    nameAr: 'نيرة نيجيرية',
    symbol: '₦',
    symbolNative: '₦',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'NG',
    countryNameEn: 'Nigeria',
    countryNameAr: 'نيجيريا',
    isActive: true,
  },
  {
    code: 'KES',
    nameEn: 'Kenyan Shilling',
    nameAr: 'شلن كيني',
    symbol: 'KSh',
    symbolNative: 'ش.ك',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'KE',
    countryNameEn: 'Kenya',
    countryNameAr: 'كينيا',
    isActive: true,
  },
  {
    code: 'TZS',
    nameEn: 'Tanzanian Shilling',
    nameAr: 'شلن تنزاني',
    symbol: 'TSh',
    symbolNative: 'ش.ت',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TZ',
    countryNameEn: 'Tanzania',
    countryNameAr: 'تنزانيا',
    isActive: true,
  },
  {
    code: 'UGX',
    nameEn: 'Ugandan Shilling',
    nameAr: 'شلن أوغندي',
    symbol: 'USh',
    symbolNative: 'ش.أ',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'UG',
    countryNameEn: 'Uganda',
    countryNameAr: 'أوغندا',
    isActive: true,
  },
  {
    code: 'GHS',
    nameEn: 'Ghanaian Cedi',
    nameAr: 'سيدي غاني',
    symbol: '₵',
    symbolNative: '₵',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'GH',
    countryNameEn: 'Ghana',
    countryNameAr: 'غانا',
    isActive: true,
  },
  {
    code: 'ETB',
    nameEn: 'Ethiopian Birr',
    nameAr: 'بر إثيوبي',
    symbol: 'Br',
    symbolNative: 'ብር',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'ET',
    countryNameEn: 'Ethiopia',
    countryNameAr: 'إثيوبيا',
    isActive: true,
  },
  {
    code: 'XOF',
    nameEn: 'West African CFA Franc',
    nameAr: 'فرنك الاتحاد المالي الأفريقي',
    symbol: 'CFA',
    symbolNative: 'ف.س.أ',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'XO',
    countryNameEn: 'West Africa',
    countryNameAr: 'غرب أفريقيا',
    isActive: true,
  },
  {
    code: 'XAF',
    nameEn: 'Central African CFA Franc',
    nameAr: 'فرنك وسط أفريقيا',
    symbol: 'FCFA',
    symbolNative: 'ف.و.أ',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'XA',
    countryNameEn: 'Central Africa',
    countryNameAr: 'وسط أفريقيا',
    isActive: true,
  },
  {
    code: 'MWK',
    nameEn: 'Malawian Kwacha',
    nameAr: 'كواشا ملاوي',
    symbol: 'MK',
    symbolNative: 'ك.م',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MW',
    countryNameEn: 'Malawi',
    countryNameAr: 'ملاوي',
    isActive: true,
  },
  {
    code: 'ZMW',
    nameEn: 'Zambian Kwacha',
    nameAr: 'كواشا زامبي',
    symbol: 'ZK',
    symbolNative: 'ك.ز',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'ZM',
    countryNameEn: 'Zambia',
    countryNameAr: 'زامبيا',
    isActive: true,
  },
  {
    code: 'BWP',
    nameEn: 'Botswana Pula',
    nameAr: 'بولا بوتسواني',
    symbol: 'P',
    symbolNative: 'P',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BW',
    countryNameEn: 'Botswana',
    countryNameAr: 'بوتسوانا',
    isActive: true,
  },
  {
    code: 'MUR',
    nameEn: 'Mauritian Rupee',
    nameAr: 'روبية موريشيوسية',
    symbol: '₨',
    symbolNative: '₨',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MU',
    countryNameEn: 'Mauritius',
    countryNameAr: 'موريشيوس',
    isActive: true,
  },

  // Additional Asian Currencies
  {
    code: 'VND',
    nameEn: 'Vietnamese Dong',
    nameAr: 'دونج فيتنامي',
    symbol: '₫',
    symbolNative: '₫',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'VN',
    countryNameEn: 'Vietnam',
    countryNameAr: 'فيتنام',
    isActive: true,
  },
  {
    code: 'PHP',
    nameEn: 'Philippine Peso',
    nameAr: 'بيزو فلبيني',
    symbol: '₱',
    symbolNative: '₱',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PH',
    countryNameEn: 'Philippines',
    countryNameAr: 'الفلبين',
    isActive: true,
  },
  {
    code: 'LKR',
    nameEn: 'Sri Lankan Rupee',
    nameAr: 'روبية سريلانكية',
    symbol: 'Rs',
    symbolNative: 'ரூ',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'LK',
    countryNameEn: 'Sri Lanka',
    countryNameAr: 'سريلانكا',
    isActive: true,
  },
  {
    code: 'MMK',
    nameEn: 'Myanmar Kyat',
    nameAr: 'كيات ميانماري',
    symbol: 'K',
    symbolNative: 'K',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MM',
    countryNameEn: 'Myanmar',
    countryNameAr: 'ميانمار',
    isActive: true,
  },
  {
    code: 'KHR',
    nameEn: 'Cambodian Riel',
    nameAr: 'ريال كمبودي',
    symbol: '៛',
    symbolNative: '៛',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'KH',
    countryNameEn: 'Cambodia',
    countryNameAr: 'كمبوديا',
    isActive: true,
  },
  {
    code: 'LAK',
    nameEn: 'Lao Kip',
    nameAr: 'كيب لاوي',
    symbol: '₭',
    symbolNative: '₭',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'LA',
    countryNameEn: 'Laos',
    countryNameAr: 'لاوس',
    isActive: true,
  },
  {
    code: 'NPR',
    nameEn: 'Nepalese Rupee',
    nameAr: 'روبية نيبالية',
    symbol: 'Rs',
    symbolNative: 'रू',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'NP',
    countryNameEn: 'Nepal',
    countryNameAr: 'نيبال',
    isActive: true,
  },
  {
    code: 'AFN',
    nameEn: 'Afghan Afghani',
    nameAr: 'أفغاني أفغانستاني',
    symbol: '؋',
    symbolNative: '؋',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AF',
    countryNameEn: 'Afghanistan',
    countryNameAr: 'أفغانستان',
    isActive: true,
  },
  {
    code: 'UZS',
    nameEn: 'Uzbekistani Som',
    nameAr: 'سوم أوزبكستاني',
    symbol: "so'm",
    symbolNative: 'сўм',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'UZ',
    countryNameEn: 'Uzbekistan',
    countryNameAr: 'أوزبكستان',
    isActive: true,
  },
  {
    code: 'KZT',
    nameEn: 'Kazakhstani Tenge',
    nameAr: 'تينغي كازاخستاني',
    symbol: '₸',
    symbolNative: '₸',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'KZ',
    countryNameEn: 'Kazakhstan',
    countryNameAr: 'كازاخستان',
    isActive: true,
  },
  {
    code: 'AZN',
    nameEn: 'Azerbaijani Manat',
    nameAr: 'مانات أذربيجاني',
    symbol: '₼',
    symbolNative: '₼',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AZ',
    countryNameEn: 'Azerbaijan',
    countryNameAr: 'أذربيجان',
    isActive: true,
  },
  {
    code: 'GEL',
    nameEn: 'Georgian Lari',
    nameAr: 'لاري جورجي',
    symbol: '₾',
    symbolNative: '₾',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'GE',
    countryNameEn: 'Georgia',
    countryNameAr: 'جورجيا',
    isActive: true,
  },
  {
    code: 'AMD',
    nameEn: 'Armenian Dram',
    nameAr: 'درام أرميني',
    symbol: '֏',
    symbolNative: '֏',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AM',
    countryNameEn: 'Armenia',
    countryNameAr: 'أرمينيا',
    isActive: true,
  },
  {
    code: 'KGS',
    nameEn: 'Kyrgyzstani Som',
    nameAr: 'سوم قيرغيزستاني',
    symbol: 'с',
    symbolNative: 'с',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'KG',
    countryNameEn: 'Kyrgyzstan',
    countryNameAr: 'قيرغيزستان',
    isActive: true,
  },
  {
    code: 'TJS',
    nameEn: 'Tajikistani Somoni',
    nameAr: 'سوموني طاجيكستاني',
    symbol: 'ЅМ',
    symbolNative: 'ЅМ',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TJ',
    countryNameEn: 'Tajikistan',
    countryNameAr: 'طاجيكستان',
    isActive: true,
  },
  {
    code: 'TMT',
    nameEn: 'Turkmenistani Manat',
    nameAr: 'مانات تركمانستاني',
    symbol: 'm',
    symbolNative: 'm',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TM',
    countryNameEn: 'Turkmenistan',
    countryNameAr: 'تركمانستان',
    isActive: true,
  },
  {
    code: 'MNT',
    nameEn: 'Mongolian Tugrik',
    nameAr: 'توغروغ منغولي',
    symbol: '₮',
    symbolNative: '₮',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'MN',
    countryNameEn: 'Mongolia',
    countryNameAr: 'منغوليا',
    isActive: true,
  },

  // European Currencies
  {
    code: 'NOK',
    nameEn: 'Norwegian Krone',
    nameAr: 'كرونة نرويجية',
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'NO',
    countryNameEn: 'Norway',
    countryNameAr: 'النرويج',
    isActive: true,
  },
  {
    code: 'SEK',
    nameEn: 'Swedish Krona',
    nameAr: 'كرونة سويدية',
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'SE',
    countryNameEn: 'Sweden',
    countryNameAr: 'السويد',
    isActive: true,
  },
  {
    code: 'DKK',
    nameEn: 'Danish Krone',
    nameAr: 'كرونة دنماركية',
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'DK',
    countryNameEn: 'Denmark',
    countryNameAr: 'الدنمارك',
    isActive: true,
  },
  {
    code: 'ISK',
    nameEn: 'Icelandic Króna',
    nameAr: 'كرونة آيسلندية',
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'IS',
    countryNameEn: 'Iceland',
    countryNameAr: 'آيسلندا',
    isActive: true,
  },
  {
    code: 'PLN',
    nameEn: 'Polish Zloty',
    nameAr: 'زلوتي بولندي',
    symbol: 'zł',
    symbolNative: 'zł',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PL',
    countryNameEn: 'Poland',
    countryNameAr: 'بولندا',
    isActive: true,
  },
  {
    code: 'CZK',
    nameEn: 'Czech Koruna',
    nameAr: 'كورونا تشيكية',
    symbol: 'Kč',
    symbolNative: 'Kč',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'CZ',
    countryNameEn: 'Czech Republic',
    countryNameAr: 'التشيك',
    isActive: true,
  },
  {
    code: 'HUF',
    nameEn: 'Hungarian Forint',
    nameAr: 'فورنت مجري',
    symbol: 'Ft',
    symbolNative: 'Ft',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'HU',
    countryNameEn: 'Hungary',
    countryNameAr: 'المجر',
    isActive: true,
  },
  {
    code: 'RON',
    nameEn: 'Romanian Leu',
    nameAr: 'ليو روماني',
    symbol: 'lei',
    symbolNative: 'lei',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'RO',
    countryNameEn: 'Romania',
    countryNameAr: 'رومانيا',
    isActive: true,
  },
  {
    code: 'BGN',
    nameEn: 'Bulgarian Lev',
    nameAr: 'ليف بلغاري',
    symbol: 'лв',
    symbolNative: 'лв',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BG',
    countryNameEn: 'Bulgaria',
    countryNameAr: 'بلغاريا',
    isActive: true,
  },
  {
    code: 'HRK',
    nameEn: 'Croatian Kuna',
    nameAr: 'كونا كرواتية',
    symbol: 'kn',
    symbolNative: 'kn',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'HR',
    countryNameEn: 'Croatia',
    countryNameAr: 'كرواتيا',
    isActive: true,
  },
  {
    code: 'UAH',
    nameEn: 'Ukrainian Hryvnia',
    nameAr: 'هريفنيا أوكرانية',
    symbol: '₴',
    symbolNative: '₴',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'UA',
    countryNameEn: 'Ukraine',
    countryNameAr: 'أوكرانيا',
    isActive: true,
  },
  {
    code: 'BYN',
    nameEn: 'Belarusian Ruble',
    nameAr: 'روبل بيلاروسي',
    symbol: 'Br',
    symbolNative: 'Br',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BY',
    countryNameEn: 'Belarus',
    countryNameAr: 'بيلاروسيا',
    isActive: true,
  },
  {
    code: 'RSD',
    nameEn: 'Serbian Dinar',
    nameAr: 'دينار صربي',
    symbol: 'дин',
    symbolNative: 'дин',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'RS',
    countryNameEn: 'Serbia',
    countryNameAr: 'صربيا',
    isActive: true,
  },

  // Latin American Currencies
  {
    code: 'ARS',
    nameEn: 'Argentine Peso',
    nameAr: 'بيزو أرجنتيني',
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'AR',
    countryNameEn: 'Argentina',
    countryNameAr: 'الأرجنتين',
    isActive: true,
  },
  {
    code: 'CLP',
    nameEn: 'Chilean Peso',
    nameAr: 'بيزو تشيلي',
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'CL',
    countryNameEn: 'Chile',
    countryNameAr: 'تشيلي',
    isActive: true,
  },
  {
    code: 'COP',
    nameEn: 'Colombian Peso',
    nameAr: 'بيزو كولومبي',
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'CO',
    countryNameEn: 'Colombia',
    countryNameAr: 'كولومبيا',
    isActive: true,
  },
  {
    code: 'PEN',
    nameEn: 'Peruvian Sol',
    nameAr: 'سول بيروفي',
    symbol: 'S/',
    symbolNative: 'S/',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PE',
    countryNameEn: 'Peru',
    countryNameAr: 'بيرو',
    isActive: true,
  },
  {
    code: 'VES',
    nameEn: 'Venezuelan Bolívar',
    nameAr: 'بوليفار فنزويلي',
    symbol: 'Bs.',
    symbolNative: 'Bs.',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'VE',
    countryNameEn: 'Venezuela',
    countryNameAr: 'فنزويلا',
    isActive: true,
  },
  {
    code: 'UYU',
    nameEn: 'Uruguayan Peso',
    nameAr: 'بيزو أوروغواي',
    symbol: '$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'UY',
    countryNameEn: 'Uruguay',
    countryNameAr: 'أوروغواي',
    isActive: true,
  },
  {
    code: 'PYG',
    nameEn: 'Paraguayan Guarani',
    nameAr: 'غواراني باراغواي',
    symbol: '₲',
    symbolNative: '₲',
    decimalDigits: 0,
    rounding: 0,
    countryCode: 'PY',
    countryNameEn: 'Paraguay',
    countryNameAr: 'باراغواي',
    isActive: true,
  },
  {
    code: 'BOB',
    nameEn: 'Bolivian Boliviano',
    nameAr: 'بوليفيانو بوليفي',
    symbol: 'Bs',
    symbolNative: 'Bs',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BO',
    countryNameEn: 'Bolivia',
    countryNameAr: 'بوليفيا',
    isActive: true,
  },
  {
    code: 'CRC',
    nameEn: 'Costa Rican Colón',
    nameAr: 'كولون كوستاريكي',
    symbol: '₡',
    symbolNative: '₡',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'CR',
    countryNameEn: 'Costa Rica',
    countryNameAr: 'كوستاريكا',
    isActive: true,
  },
  {
    code: 'GTQ',
    nameEn: 'Guatemalan Quetzal',
    nameAr: 'كتزال غواتيمالي',
    symbol: 'Q',
    symbolNative: 'Q',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'GT',
    countryNameEn: 'Guatemala',
    countryNameAr: 'غواتيمالا',
    isActive: true,
  },
  {
    code: 'HNL',
    nameEn: 'Honduran Lempira',
    nameAr: 'ليمبيرا هندوراسي',
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'HN',
    countryNameEn: 'Honduras',
    countryNameAr: 'هندوراس',
    isActive: true,
  },
  {
    code: 'NIO',
    nameEn: 'Nicaraguan Córdoba',
    nameAr: 'كوردوبا نيكاراغوا',
    symbol: 'C$',
    symbolNative: 'C$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'NI',
    countryNameEn: 'Nicaragua',
    countryNameAr: 'نيكاراغوا',
    isActive: true,
  },
  {
    code: 'PAB',
    nameEn: 'Panamanian Balboa',
    nameAr: 'بالبوا بنمي',
    symbol: 'B/.',
    symbolNative: 'B/.',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PA',
    countryNameEn: 'Panama',
    countryNameAr: 'بنما',
    isActive: true,
  },

  // Oceania & Pacific
  {
    code: 'NZD',
    nameEn: 'New Zealand Dollar',
    nameAr: 'دولار نيوزيلندي',
    symbol: 'NZ$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'NZ',
    countryNameEn: 'New Zealand',
    countryNameAr: 'نيوزيلندا',
    isActive: true,
  },
  {
    code: 'FJD',
    nameEn: 'Fijian Dollar',
    nameAr: 'دولار فيجي',
    symbol: 'FJ$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'FJ',
    countryNameEn: 'Fiji',
    countryNameAr: 'فيجي',
    isActive: true,
  },
  {
    code: 'PGK',
    nameEn: 'Papua New Guinean Kina',
    nameAr: 'كينا بابوا غينيا الجديدة',
    symbol: 'K',
    symbolNative: 'K',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'PG',
    countryNameEn: 'Papua New Guinea',
    countryNameAr: 'بابوا غينيا الجديدة',
    isActive: true,
  },

  // Caribbean
  {
    code: 'JMD',
    nameEn: 'Jamaican Dollar',
    nameAr: 'دولار جامايكي',
    symbol: 'J$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'JM',
    countryNameEn: 'Jamaica',
    countryNameAr: 'جامايكا',
    isActive: true,
  },
  {
    code: 'TTD',
    nameEn: 'Trinidad and Tobago Dollar',
    nameAr: 'دولار ترينيداد وتوباغو',
    symbol: 'TT$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'TT',
    countryNameEn: 'Trinidad and Tobago',
    countryNameAr: 'ترينيداد وتوباغو',
    isActive: true,
  },
  {
    code: 'BSD',
    nameEn: 'Bahamian Dollar',
    nameAr: 'دولار باهامي',
    symbol: 'B$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BS',
    countryNameEn: 'Bahamas',
    countryNameAr: 'باهاماس',
    isActive: true,
  },
  {
    code: 'BBD',
    nameEn: 'Barbadian Dollar',
    nameAr: 'دولار بربادوسي',
    symbol: 'Bds$',
    symbolNative: '$',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'BB',
    countryNameEn: 'Barbados',
    countryNameAr: 'بربادوس',
    isActive: true,
  },

  // Additional
  {
    code: 'ILS',
    nameEn: 'Israeli New Shekel',
    nameAr: 'شيكل إسرائيلي',
    symbol: '₪',
    symbolNative: '₪',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'IL',
    countryNameEn: 'Israel',
    countryNameAr: 'إسرائيل',
    isActive: true,
  },
  {
    code: 'IRR',
    nameEn: 'Iranian Rial',
    nameAr: 'ريال إيراني',
    symbol: '﷼',
    symbolNative: '﷼',
    decimalDigits: 2,
    rounding: 0,
    countryCode: 'IR',
    countryNameEn: 'Iran',
    countryNameAr: 'إيران',
    isActive: true,
  },
];

// Mock exchange rates (updated daily in real system)
export const exchangeRates: ExchangeRate[] = [
  // SAR to major currencies
  {
    id: 'SAR-USD',
    fromCurrency: 'SAR',
    toCurrency: 'USD',
    rate: 0.2666,
    inverseRate: 3.75,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-EUR',
    fromCurrency: 'SAR',
    toCurrency: 'EUR',
    rate: 0.2453,
    inverseRate: 4.08,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-GBP',
    fromCurrency: 'SAR',
    toCurrency: 'GBP',
    rate: 0.2106,
    inverseRate: 4.75,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-AED',
    fromCurrency: 'SAR',
    toCurrency: 'AED',
    rate: 0.9789,
    inverseRate: 1.0216,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-KWD',
    fromCurrency: 'SAR',
    toCurrency: 'KWD',
    rate: 0.0819,
    inverseRate: 12.21,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-BHD',
    fromCurrency: 'SAR',
    toCurrency: 'BHD',
    rate: 0.1004,
    inverseRate: 9.96,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-OMR',
    fromCurrency: 'SAR',
    toCurrency: 'OMR',
    rate: 0.1026,
    inverseRate: 9.75,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-QAR',
    fromCurrency: 'SAR',
    toCurrency: 'QAR',
    rate: 0.9702,
    inverseRate: 1.0307,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-EGP',
    fromCurrency: 'SAR',
    toCurrency: 'EGP',
    rate: 8.23,
    inverseRate: 0.1215,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-JOD',
    fromCurrency: 'SAR',
    toCurrency: 'JOD',
    rate: 0.1890,
    inverseRate: 5.29,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-TRY',
    fromCurrency: 'SAR',
    toCurrency: 'TRY',
    rate: 8.15,
    inverseRate: 0.1227,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-INR',
    fromCurrency: 'SAR',
    toCurrency: 'INR',
    rate: 22.10,
    inverseRate: 0.0452,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-PKR',
    fromCurrency: 'SAR',
    toCurrency: 'PKR',
    rate: 74.32,
    inverseRate: 0.0135,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-CNY',
    fromCurrency: 'SAR',
    toCurrency: 'CNY',
    rate: 1.92,
    inverseRate: 0.5208,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
  {
    id: 'SAR-JPY',
    fromCurrency: 'SAR',
    toCurrency: 'JPY',
    rate: 39.85,
    inverseRate: 0.0251,
    effectiveDate: '2024-02-28',
    source: 'SAMA',
    isActive: true,
    lastUpdated: '2024-02-28T08:00:00',
  },
];

// Helper functions
export const getBaseCurrency = (): Currency => {
  return globalCurrencies.find(c => c.isBaseCurrency) || globalCurrencies[0];
};

export const getCurrencyByCode = (code: string): Currency | undefined => {
  return globalCurrencies.find(c => c.code === code);
};

export const getExchangeRate = (fromCurrency: string, toCurrency: string): number => {
  if (fromCurrency === toCurrency) return 1;
  
  const rate = exchangeRates.find(
    r => r.fromCurrency === fromCurrency && r.toCurrency === toCurrency && r.isActive
  );
  
  if (rate) return rate.rate;
  
  // Try inverse rate
  const inverseRate = exchangeRates.find(
    r => r.fromCurrency === toCurrency && r.toCurrency === fromCurrency && r.isActive
  );
  
  if (inverseRate) return inverseRate.inverseRate;
  
  return 1; // Default to 1 if no rate found
};

export const convertCurrency = (
  amount: number,
  fromCurrency: string,
  toCurrency: string
): number => {
  const rate = getExchangeRate(fromCurrency, toCurrency);
  return amount * rate;
};

export const formatCurrencyAmount = (
  amount: number,
  currencyCode: string,
  locale: string = 'en'
): string => {
  const currency = getCurrencyByCode(currencyCode);
  if (!currency) return amount.toFixed(2);
  
  const formattedAmount = amount.toLocaleString(locale, {
    minimumFractionDigits: currency.decimalDigits,
    maximumFractionDigits: currency.decimalDigits,
  });
  
  const symbol = locale === 'ar' ? currency.symbolNative : currency.symbol;
  
  return locale === 'ar' 
    ? `${formattedAmount} ${symbol}`
    : `${symbol} ${formattedAmount}`;
};

export const getActiveCurrencies = (): Currency[] => {
  return globalCurrencies.filter(c => c.isActive);
};

export const getCurrenciesByRegion = (region: 'middle-east' | 'asia' | 'europe' | 'americas' | 'africa') => {
  const middleEastCodes = ['SAR', 'AED', 'KWD', 'BHD', 'OMR', 'QAR', 'JOD', 'EGP', 'LBP', 'SYP', 'IQD'];
  const asiaCodes = ['CNY', 'JPY', 'INR', 'KRW', 'SGD', 'MYR', 'IDR', 'THB', 'PKR', 'BDT'];
  const europeCodes = ['EUR', 'GBP', 'CHF', 'RUB', 'TRY'];
  const americasCodes = ['USD', 'CAD', 'MXN', 'BRL'];
  const africaCodes = ['MAD', 'TND', 'LYD', 'DZD', 'SDG', 'ZAR'];
  
  let codes: string[] = [];
  switch (region) {
    case 'middle-east':
      codes = middleEastCodes;
      break;
    case 'asia':
      codes = asiaCodes;
      break;
    case 'europe':
      codes = europeCodes;
      break;
    case 'americas':
      codes = americasCodes;
      break;
    case 'africa':
      codes = africaCodes;
      break;
  }
  
  return globalCurrencies.filter(c => codes.includes(c.code));
};