/**
 * Comprehensive Inventory Database - IAS 2 Compliant
 * Universal structure suitable for all types of businesses
 * Total: 500+ inventory items across all industries
 */

export interface InventoryItem {
  code: string;
  nameEn: string;
  nameAr: string;
  category: string;
  subCategory: string;
  industry: string[];
  type: 'raw_material' | 'wip' | 'finished_goods' | 'merchandise' | 'spare_parts' | 'consumables' | 'supplies';
  unit: string;
  unitAr: string;
  costPrice: number;
  sellingPrice: number;
  minStock: number;
  maxStock: number;
  reorderPoint: number;
  safetyStock?: number;
  currentStock: number;
  warehouseLocation: string;
  supplier?: string;
  barcode?: string;
  sku?: string;
  expiryTracking: boolean;
  batchTracking: boolean;
  serialTracking: boolean;
  taxRate: number;
  status: 'active' | 'inactive' | 'discontinued';
  description?: string;
}

export const universalInventoryItems: InventoryItem[] = [
  
  // ==============================================
  // 1. CHEMICAL MANUFACTURING (معمل منتجات كيماوية)
  // ==============================================
  
  // Raw Materials
  {
    code: 'CHM-RM-001',
    nameEn: 'Sulfuric Acid 98%',
    nameAr: 'حمض الكبريتيك 98%',
    category: 'Chemicals',
    subCategory: 'Industrial Acids',
    industry: ['Chemical Manufacturing'],
    type: 'raw_material',
    unit: 'Liter',
    unitAr: 'لتر',
    costPrice: 25,
    sellingPrice: 0,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'A-01-H',
    barcode: '8901234567890',
    sku: 'CHM-RM-001',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
    description: 'High purity industrial grade sulfuric acid',
  },
  {
    code: 'CHM-RM-002',
    nameEn: 'Sodium Hydroxide (Caustic Soda)',
    nameAr: 'هيدروكسيد الصوديوم',
    category: 'Chemicals',
    subCategory: 'Industrial Bases',
    industry: ['Chemical Manufacturing'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 15,
    sellingPrice: 0,
    minStock: 1000,
    maxStock: 10000,
    reorderPoint: 2000,
    currentStock: 5000,
    warehouseLocation: 'A-02-H',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CHM-RM-003',
    nameEn: 'Ethanol 99.9%',
    nameAr: 'إيثانول 99.9%',
    category: 'Chemicals',
    subCategory: 'Solvents',
    industry: ['Chemical Manufacturing', 'Pharmaceutical'],
    type: 'raw_material',
    unit: 'Liter',
    unitAr: 'لتر',
    costPrice: 18,
    sellingPrice: 0,
    minStock: 300,
    maxStock: 3000,
    reorderPoint: 600,
    currentStock: 1500,
    warehouseLocation: 'A-03-H',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CHM-RM-004',
    nameEn: 'Titanium Dioxide',
    nameAr: 'ثاني أكسيد التيتانيوم',
    category: 'Chemicals',
    subCategory: 'Pigments',
    industry: ['Chemical Manufacturing', 'Paint Manufacturing'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 35,
    sellingPrice: 0,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 400,
    currentStock: 1000,
    warehouseLocation: 'A-04-H',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CHM-RM-005',
    nameEn: 'Polyethylene Resin',
    nameAr: 'راتنج البولي إيثيلين',
    category: 'Chemicals',
    subCategory: 'Polymers',
    industry: ['Chemical Manufacturing', 'Plastic Manufacturing'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 22,
    sellingPrice: 0,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'A-05-H',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // Finished Products
  {
    code: 'CHM-FG-001',
    nameEn: 'Industrial Detergent 5L',
    nameAr: 'منظف صناعي 5 لتر',
    category: 'Cleaning Products',
    subCategory: 'Industrial Cleaners',
    industry: ['Chemical Manufacturing'],
    type: 'finished_goods',
    unit: 'Bottle',
    unitAr: 'عبوة',
    costPrice: 45,
    sellingPrice: 75,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'B-01-C',
    barcode: '8901234567897',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CHM-FG-002',
    nameEn: 'Paint - White Matt 20L',
    nameAr: 'دهان أبيض مطفي 20 لتر',
    category: 'Paints',
    subCategory: 'Wall Paint',
    industry: ['Chemical Manufacturing'],
    type: 'finished_goods',
    unit: 'Can',
    unitAr: 'جالون',
    costPrice: 180,
    sellingPrice: 300,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'B-02-C',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 2. FOOD MANUFACTURING (معمل منتجات غذائية)
  // ==============================================
  
  // Raw Materials
  {
    code: 'FOOD-RM-001',
    nameEn: 'Wheat Flour Grade A',
    nameAr: 'دقيق قمح درجة أولى',
    category: 'Food Ingredients',
    subCategory: 'Grains & Flours',
    industry: ['Food Manufacturing', 'Bakery'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 2.5,
    sellingPrice: 0,
    minStock: 1000,
    maxStock: 10000,
    reorderPoint: 2000,
    currentStock: 5000,
    warehouseLocation: 'F-01-D',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FOOD-RM-002',
    nameEn: 'White Sugar Refined',
    nameAr: 'سكر أبيض مكرر',
    category: 'Food Ingredients',
    subCategory: 'Sweeteners',
    industry: ['Food Manufacturing', 'Bakery', 'Restaurant'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 3,
    sellingPrice: 0,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'F-02-D',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FOOD-RM-003',
    nameEn: 'Vegetable Oil - Refined',
    nameAr: 'زيت نباتي مكرر',
    category: 'Food Ingredients',
    subCategory: 'Oils & Fats',
    industry: ['Food Manufacturing', 'Restaurant'],
    type: 'raw_material',
    unit: 'Liter',
    unitAr: 'لتر',
    costPrice: 8,
    sellingPrice: 0,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'F-03-D',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FOOD-RM-004',
    nameEn: 'Fresh Milk 3.5% Fat',
    nameAr: 'حليب طازج 3.5% دسم',
    category: 'Food Ingredients',
    subCategory: 'Dairy Products',
    industry: ['Food Manufacturing', 'Restaurant'],
    type: 'raw_material',
    unit: 'Liter',
    unitAr: 'لتر',
    costPrice: 4,
    sellingPrice: 0,
    minStock: 200,
    maxStock: 1000,
    reorderPoint: 300,
    currentStock: 500,
    warehouseLocation: 'F-04-R',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FOOD-RM-005',
    nameEn: 'Tomato Paste Concentrate',
    nameAr: 'معجون طماطم مركز',
    category: 'Food Ingredients',
    subCategory: 'Preserves',
    industry: ['Food Manufacturing', 'Restaurant'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 12,
    sellingPrice: 0,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'F-05-D',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },

  // Finished Products
  {
    code: 'FOOD-FG-001',
    nameEn: 'Chocolate Cookies 250g',
    nameAr: 'بسكويت بالشوكولاتة 250 جرام',
    category: 'Bakery Products',
    subCategory: 'Cookies',
    industry: ['Food Manufacturing'],
    type: 'finished_goods',
    unit: 'Pack',
    unitAr: 'علبة',
    costPrice: 8,
    sellingPrice: 15,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 400,
    currentStock: 1000,
    warehouseLocation: 'F-10-C',
    barcode: '6281234567890',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'FOOD-FG-002',
    nameEn: 'Orange Juice 1L',
    nameAr: 'عصير برتقال 1 لتر',
    category: 'Beverages',
    subCategory: 'Fruit Juices',
    industry: ['Food Manufacturing'],
    type: 'finished_goods',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 12,
    sellingPrice: 20,
    minStock: 150,
    maxStock: 1500,
    reorderPoint: 300,
    currentStock: 750,
    warehouseLocation: 'F-11-R',
    barcode: '6281234567891',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 3. CONSTRUCTION MATERIALS (معمل منتجات إنشائية)
  // ==============================================
  
  {
    code: 'CONST-RM-001',
    nameEn: 'Portland Cement Grade 42.5',
    nameAr: 'أسمنت بورتلاند درجة 42.5',
    category: 'Construction Materials',
    subCategory: 'Cement',
    industry: ['Construction Manufacturing', 'Construction', 'Hardware Store'],
    type: 'raw_material',
    unit: 'Bag 50Kg',
    unitAr: 'شيكارة 50 كجم',
    costPrice: 35,
    sellingPrice: 55,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'C-01-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CONST-RM-002',
    nameEn: 'Steel Rebar 12mm',
    nameAr: 'حديد تسليح 12 ملم',
    category: 'Construction Materials',
    subCategory: 'Steel',
    industry: ['Construction Manufacturing', 'Construction'],
    type: 'raw_material',
    unit: 'Ton',
    unitAr: 'طن',
    costPrice: 3500,
    sellingPrice: 4500,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    currentStock: 50,
    warehouseLocation: 'C-02-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CONST-FG-001',
    nameEn: 'Concrete Block 20x40cm',
    nameAr: 'بلك خرساني 20×40 سم',
    category: 'Construction Materials',
    subCategory: 'Blocks',
    industry: ['Construction Manufacturing', 'Construction', 'Hardware Store'],
    type: 'finished_goods',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 3,
    sellingPrice: 5,
    minStock: 1000,
    maxStock: 10000,
    reorderPoint: 2000,
    currentStock: 5000,
    warehouseLocation: 'C-03-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CONST-FG-002',
    nameEn: 'Ceramic Tiles 60x60cm White',
    nameAr: 'بلاط سيراميك 60×60 أبيض',
    category: 'Construction Materials',
    subCategory: 'Tiles',
    industry: ['Construction Manufacturing', 'Construction', 'Hardware Store'],
    type: 'finished_goods',
    unit: 'Box',
    unitAr: 'كرتونة',
    costPrice: 85,
    sellingPrice: 150,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'C-04-C',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 4. MINING & METALS (تعدين)
  // ==============================================
  
  {
    code: 'MIN-RM-001',
    nameEn: 'Iron Ore 65% Fe',
    nameAr: 'خام حديد 65% حديد',
    category: 'Mining Products',
    subCategory: 'Iron Ore',
    industry: ['Mining', 'Metal Manufacturing'],
    type: 'raw_material',
    unit: 'Ton',
    unitAr: 'طن',
    costPrice: 850,
    sellingPrice: 1200,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'M-01-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'MIN-RM-002',
    nameEn: 'Copper Concentrate',
    nameAr: 'مركز النحاس',
    category: 'Mining Products',
    subCategory: 'Copper',
    industry: ['Mining', 'Metal Manufacturing'],
    type: 'raw_material',
    unit: 'Ton',
    unitAr: 'طن',
    costPrice: 4500,
    sellingPrice: 6000,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 40,
    currentStock: 100,
    warehouseLocation: 'M-02-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'MIN-FG-001',
    nameEn: 'Aluminum Ingot 99.7%',
    nameAr: 'سبيكة ألومنيوم 99.7%',
    category: 'Metal Products',
    subCategory: 'Aluminum',
    industry: ['Mining', 'Metal Manufacturing'],
    type: 'finished_goods',
    unit: 'Ton',
    unitAr: 'طن',
    costPrice: 12000,
    sellingPrice: 15000,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    currentStock: 50,
    warehouseLocation: 'M-03-S',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 5. FOOD RETAIL (تجارة مواد غذائية)
  // ==============================================
  
  {
    code: 'FRT-001',
    nameEn: 'Rice Basmati 5Kg',
    nameAr: 'أرز بسمتي 5 كجم',
    category: 'Food Retail',
    subCategory: 'Grains',
    industry: ['Food Retail', 'Grocery Store', 'Supermarket'],
    type: 'merchandise',
    unit: 'Bag',
    unitAr: 'كيس',
    costPrice: 28,
    sellingPrice: 45,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'R-01-D',
    barcode: '6281111111111',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FRT-002',
    nameEn: 'Olive Oil Extra Virgin 1L',
    nameAr: 'زيت زيتون بكر ممتاز 1 لتر',
    category: 'Food Retail',
    subCategory: 'Oils',
    industry: ['Food Retail', 'Grocery Store'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 45,
    sellingPrice: 75,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'R-02-D',
    barcode: '6281111111112',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FRT-003',
    nameEn: 'Fresh Chicken 1Kg',
    nameAr: 'دجاج طازج 1 كجم',
    category: 'Food Retail',
    subCategory: 'Meat & Poultry',
    industry: ['Food Retail', 'Grocery Store', 'Restaurant'],
    type: 'merchandise',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 18,
    sellingPrice: 28,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 100,
    currentStock: 150,
    warehouseLocation: 'R-03-F',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FRT-004',
    nameEn: 'Cheddar Cheese 500g',
    nameAr: 'جبن شيدر 500 جرام',
    category: 'Food Retail',
    subCategory: 'Dairy',
    industry: ['Food Retail', 'Grocery Store', 'Restaurant'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'علبة',
    costPrice: 22,
    sellingPrice: 35,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'R-04-R',
    barcode: '6281111111113',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'FRT-005',
    nameEn: 'Coffee Beans Arabica 250g',
    nameAr: 'بن عربي 250 جرام',
    category: 'Food Retail',
    subCategory: 'Beverages',
    industry: ['Food Retail', 'Grocery Store', 'Coffee Shop'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'علبة',
    costPrice: 35,
    sellingPrice: 60,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'R-05-D',
    barcode: '6281111111114',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 6. COSMETICS RETAIL (تجارة مواد تجميلية)
  // ==============================================
  
  {
    code: 'COS-001',
    nameEn: 'Face Cream Anti-Aging 50ml',
    nameAr: 'كريم للوجه مضاد للشيخوخة 50 مل',
    category: 'Cosmetics',
    subCategory: 'Skin Care',
    industry: ['Cosmetics Retail', 'Pharmacy', 'Beauty Salon'],
    type: 'merchandise',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 85,
    sellingPrice: 150,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'CS-01-C',
    barcode: '6282222222221',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'COS-002',
    nameEn: 'Shampoo Keratin 400ml',
    nameAr: 'شامبو بالكيراتين 400 مل',
    category: 'Cosmetics',
    subCategory: 'Hair Care',
    industry: ['Cosmetics Retail', 'Beauty Salon'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 35,
    sellingPrice: 65,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'CS-02-C',
    barcode: '6282222222222',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'COS-003',
    nameEn: 'Lipstick Matte Red',
    nameAr: 'أحمر شفاه مطفي أحمر',
    category: 'Cosmetics',
    subCategory: 'Makeup',
    industry: ['Cosmetics Retail', 'Beauty Salon'],
    type: 'merchandise',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 42,
    sellingPrice: 80,
    minStock: 40,
    maxStock: 400,
    reorderPoint: 80,
    currentStock: 200,
    warehouseLocation: 'CS-03-C',
    barcode: '6282222222223',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'COS-004',
    nameEn: 'Perfume for Men 100ml',
    nameAr: 'عطر رجالي 100 مل',
    category: 'Cosmetics',
    subCategory: 'Fragrances',
    industry: ['Cosmetics Retail', 'Luxury Retail'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 120,
    sellingPrice: 250,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 40,
    currentStock: 100,
    warehouseLocation: 'CS-04-S',
    barcode: '6282222222224',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'COS-005',
    nameEn: 'Sunscreen SPF 50+ 75ml',
    nameAr: 'واقي شمس SPF 50+ 75 مل',
    category: 'Cosmetics',
    subCategory: 'Sun Care',
    industry: ['Cosmetics Retail', 'Pharmacy'],
    type: 'merchandise',
    unit: 'Tube',
    unitAr: 'أنبوب',
    costPrice: 55,
    sellingPrice: 95,
    minStock: 40,
    maxStock: 400,
    reorderPoint: 80,
    currentStock: 200,
    warehouseLocation: 'CS-05-C',
    barcode: '6282222222225',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 7. AUTO PARTS (قطع غيار متنوعة)
  // ==============================================
  
  {
    code: 'AUTO-001',
    nameEn: 'Engine Oil 5W-30 4L',
    nameAr: 'زيت محرك 5W-30 4 لتر',
    category: 'Auto Parts',
    subCategory: 'Lubricants',
    industry: ['Auto Parts', 'Service Center'],
    type: 'merchandise',
    unit: 'Can',
    unitAr: 'جالون',
    costPrice: 45,
    sellingPrice: 75,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'AP-01-D',
    barcode: '6283333333331',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'AUTO-002',
    nameEn: 'Brake Pads Front - Universal',
    nameAr: 'فحمات فرامل أمامية - عامة',
    category: 'Auto Parts',
    subCategory: 'Brake System',
    industry: ['Auto Parts', 'Service Center'],
    type: 'spare_parts',
    unit: 'Set',
    unitAr: 'طقم',
    costPrice: 85,
    sellingPrice: 150,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'AP-02-C',
    barcode: '6283333333332',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'AUTO-003',
    nameEn: 'Air Filter - Toyota Camry',
    nameAr: 'فلتر هواء - تويوتا كامري',
    category: 'Auto Parts',
    subCategory: 'Filters',
    industry: ['Auto Parts', 'Service Center'],
    type: 'spare_parts',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 25,
    sellingPrice: 45,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'AP-03-C',
    barcode: '6283333333333',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'AUTO-004',
    nameEn: 'Battery 12V 70Ah',
    nameAr: 'بطارية 12 فولت 70 أمبير',
    category: 'Auto Parts',
    subCategory: 'Electrical',
    industry: ['Auto Parts', 'Service Center'],
    type: 'spare_parts',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 280,
    sellingPrice: 450,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 40,
    currentStock: 100,
    warehouseLocation: 'AP-04-S',
    barcode: '6283333333334',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'AUTO-005',
    nameEn: 'Tire 195/65 R15',
    nameAr: 'إطار 195/65 R15',
    category: 'Auto Parts',
    subCategory: 'Tires',
    industry: ['Auto Parts', 'Service Center'],
    type: 'spare_parts',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 220,
    sellingPrice: 350,
    minStock: 40,
    maxStock: 400,
    reorderPoint: 80,
    currentStock: 200,
    warehouseLocation: 'AP-05-Y',
    barcode: '6283333333335',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 8. HOSPITAL & MEDICAL (مستشفى)
  // ==============================================
  
  {
    code: 'MED-001',
    nameEn: 'Surgical Gloves Latex Size M',
    nameAr: 'قفازات جراحية لاتكس مقاس وسط',
    category: 'Medical Supplies',
    subCategory: 'PPE',
    industry: ['Hospital', 'Clinic', 'Pharmacy'],
    type: 'consumables',
    unit: 'Box 100pcs',
    unitAr: 'علبة 100 قطعة',
    costPrice: 35,
    sellingPrice: 60,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'H-01-C',
    barcode: '6284444444441',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'MED-002',
    nameEn: 'Disposable Syringe 5ml',
    nameAr: 'حقنة يمكن التخلص منها 5 مل',
    category: 'Medical Supplies',
    subCategory: 'Injection Supplies',
    industry: ['Hospital', 'Clinic', 'Pharmacy'],
    type: 'consumables',
    unit: 'Box 100pcs',
    unitAr: 'علبة 100 قطعة',
    costPrice: 18,
    sellingPrice: 30,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 400,
    currentStock: 1000,
    warehouseLocation: 'H-02-C',
    barcode: '6284444444442',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'MED-003',
    nameEn: 'Paracetamol 500mg Tablets',
    nameAr: 'باراسيتامول 500 ملجم أقراص',
    category: 'Pharmaceuticals',
    subCategory: 'Pain Relief',
    industry: ['Hospital', 'Pharmacy'],
    type: 'merchandise',
    unit: 'Strip 10 Tablets',
    unitAr: 'شريط 10 أقراص',
    costPrice: 3,
    sellingPrice: 6,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'H-03-P',
    barcode: '6284444444443',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'MED-004',
    nameEn: 'Blood Pressure Monitor Digital',
    nameAr: 'جهاز قياس ضغط الدم رقمي',
    category: 'Medical Equipment',
    subCategory: 'Diagnostic Equipment',
    industry: ['Hospital', 'Clinic'],
    type: 'spare_parts',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 250,
    sellingPrice: 450,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    currentStock: 50,
    warehouseLocation: 'H-04-S',
    barcode: '6284444444444',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'MED-005',
    nameEn: 'Surgical Mask 3-Ply',
    nameAr: 'كمامة جراحية 3 طبقات',
    category: 'Medical Supplies',
    subCategory: 'PPE',
    industry: ['Hospital', 'Clinic', 'Pharmacy'],
    type: 'consumables',
    unit: 'Box 50pcs',
    unitAr: 'علبة 50 قطعة',
    costPrice: 12,
    sellingPrice: 20,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 400,
    currentStock: 1000,
    warehouseLocation: 'H-05-C',
    barcode: '6284444444445',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },

  // ==============================================
  // 9. RESTAURANT & CATERING (مطاعم)
  // ==============================================
  
  {
    code: 'REST-001',
    nameEn: 'Fresh Tomatoes',
    nameAr: 'طماطم طازجة',
    category: 'Fresh Produce',
    subCategory: 'Vegetables',
    industry: ['Restaurant', 'Catering', 'Food Retail'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 4,
    sellingPrice: 0,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 100,
    currentStock: 150,
    warehouseLocation: 'RS-01-F',
    expiryTracking: true,
    batchTracking: false,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'REST-002',
    nameEn: 'Ground Beef Premium',
    nameAr: 'لحم بقري مفروم ممتاز',
    category: 'Meat',
    subCategory: 'Beef',
    industry: ['Restaurant', 'Catering'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 38,
    sellingPrice: 0,
    minStock: 30,
    maxStock: 200,
    reorderPoint: 60,
    currentStock: 100,
    warehouseLocation: 'RS-02-F',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'REST-003',
    nameEn: 'Mozzarella Cheese Shredded',
    nameAr: 'جبن موتزاريلا مبشورة',
    category: 'Dairy',
    subCategory: 'Cheese',
    industry: ['Restaurant', 'Catering', 'Pizza Shop'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 28,
    sellingPrice: 0,
    minStock: 20,
    maxStock: 150,
    reorderPoint: 40,
    currentStock: 80,
    warehouseLocation: 'RS-03-R',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'REST-004',
    nameEn: 'Disposable Food Container Large',
    nameAr: 'علبة طعام كبيرة يمكن التخلص منها',
    category: 'Packaging',
    subCategory: 'Food Containers',
    industry: ['Restaurant', 'Catering'],
    type: 'supplies',
    unit: 'Pack 50pcs',
    unitAr: 'حزمة 50 قطعة',
    costPrice: 25,
    sellingPrice: 0,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'RS-04-D',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'REST-005',
    nameEn: 'Coffee Beans Ethiopian',
    nameAr: 'بن إثيوبي',
    category: 'Beverages',
    subCategory: 'Coffee',
    industry: ['Restaurant', 'Coffee Shop'],
    type: 'raw_material',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 85,
    sellingPrice: 0,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    currentStock: 50,
    warehouseLocation: 'RS-05-D',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 10. IT & INTERNET SERVICES (خدمات الإنترنت)
  // ==============================================
  
  {
    code: 'IT-001',
    nameEn: 'Network Cable Cat6 305m',
    nameAr: 'كيبل شبكات Cat6 305 متر',
    category: 'IT Equipment',
    subCategory: 'Networking',
    industry: ['IT Services', 'Telecom'],
    type: 'supplies',
    unit: 'Roll',
    unitAr: 'بكرة',
    costPrice: 180,
    sellingPrice: 300,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    currentStock: 50,
    warehouseLocation: 'IT-01-C',
    barcode: '6285555555551',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'IT-002',
    nameEn: 'Wireless Router Dual Band',
    nameAr: 'راوتر لاسلكي ثنائي النطاق',
    category: 'IT Equipment',
    subCategory: 'Networking',
    industry: ['IT Services', 'Telecom'],
    type: 'merchandise',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 250,
    sellingPrice: 450,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 40,
    currentStock: 100,
    warehouseLocation: 'IT-02-S',
    barcode: '6285555555552',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'IT-003',
    nameEn: 'SSD Hard Drive 1TB',
    nameAr: 'هارد SSD 1 تيرابايت',
    category: 'IT Equipment',
    subCategory: 'Storage',
    industry: ['IT Services', 'Computer Shop'],
    type: 'spare_parts',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 350,
    sellingPrice: 550,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'IT-03-S',
    barcode: '6285555555553',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'IT-004',
    nameEn: 'Fiber Optic Cable Single Mode',
    nameAr: 'كيبل ألياف ضوئية أحادي النمط',
    category: 'IT Equipment',
    subCategory: 'Networking',
    industry: ['IT Services', 'Telecom'],
    type: 'supplies',
    unit: 'Meter',
    unitAr: 'متر',
    costPrice: 8,
    sellingPrice: 15,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 1000,
    currentStock: 2500,
    warehouseLocation: 'IT-04-C',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'IT-005',
    nameEn: 'Server Rack 42U',
    nameAr: 'خزانة خوادم 42U',
    category: 'IT Equipment',
    subCategory: 'Infrastructure',
    industry: ['IT Services', 'Data Center'],
    type: 'merchandise',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 2500,
    sellingPrice: 4000,
    minStock: 5,
    maxStock: 50,
    reorderPoint: 10,
    currentStock: 25,
    warehouseLocation: 'IT-05-W',
    barcode: '6285555555554',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: true,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 11. CONSTRUCTION & CONTRACTING (المقاولات)
  // ==============================================
  
  {
    code: 'CNTR-001',
    nameEn: 'Concrete Ready Mix M30',
    nameAr: 'خرسانة جاهزة M30',
    category: 'Construction Materials',
    subCategory: 'Concrete',
    industry: ['Construction', 'Contracting'],
    type: 'raw_material',
    unit: 'Cubic Meter',
    unitAr: 'متر مكعب',
    costPrice: 280,
    sellingPrice: 0,
    minStock: 0,
    maxStock: 0,
    reorderPoint: 0,
    currentStock: 0,
    warehouseLocation: 'CN-01-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CNTR-002',
    nameEn: 'Steel Rebar Various Sizes',
    nameAr: 'حديد تسليح مقاسات متنوعة',
    category: 'Construction Materials',
    subCategory: 'Steel',
    industry: ['Construction', 'Contracting'],
    type: 'raw_material',
    unit: 'Ton',
    unitAr: 'طن',
    costPrice: 3800,
    sellingPrice: 0,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 40,
    currentStock: 100,
    warehouseLocation: 'CN-02-Y',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CNTR-003',
    nameEn: 'Plywood 18mm 122x244cm',
    nameAr: 'خشب أبلكاش 18 ملم 122×244 سم',
    category: 'Construction Materials',
    subCategory: 'Wood',
    industry: ['Construction', 'Contracting', 'Carpentry'],
    type: 'raw_material',
    unit: 'Sheet',
    unitAr: 'لوح',
    costPrice: 85,
    sellingPrice: 0,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'CN-03-C',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CNTR-004',
    nameEn: 'Gypsum Board 12mm',
    nameAr: 'لوح جبس بورد 12 ملم',
    category: 'Construction Materials',
    subCategory: 'Drywall',
    industry: ['Construction', 'Contracting'],
    type: 'raw_material',
    unit: 'Sheet',
    unitAr: 'لوح',
    costPrice: 18,
    sellingPrice: 0,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'CN-04-C',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'CNTR-005',
    nameEn: 'Electrical Wire 2.5mm',
    nameAr: 'سلك كهربائي 2.5 ملم',
    category: 'Electrical Materials',
    subCategory: 'Wiring',
    industry: ['Construction', 'Contracting', 'Electrical'],
    type: 'raw_material',
    unit: 'Roll 100m',
    unitAr: 'بكرة 100 متر',
    costPrice: 120,
    sellingPrice: 0,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'CN-05-C',
    batchTracking: true,
    expiryTracking: false,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 12. SMALL RETAIL & GROCERY (محال صغيرة)
  // ==============================================
  
  {
    code: 'GRC-001',
    nameEn: 'Bread White Sliced',
    nameAr: 'خبز توست أبيض',
    category: 'Bakery',
    subCategory: 'Bread',
    industry: ['Grocery Store', 'Small Retail'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'كيس',
    costPrice: 3,
    sellingPrice: 5,
    minStock: 50,
    maxStock: 200,
    reorderPoint: 80,
    currentStock: 120,
    warehouseLocation: 'GR-01-D',
    barcode: '6286666666661',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'GRC-002',
    nameEn: 'Eggs White Large',
    nameAr: 'بيض أبيض كبير',
    category: 'Dairy & Eggs',
    subCategory: 'Eggs',
    industry: ['Grocery Store', 'Small Retail'],
    type: 'merchandise',
    unit: 'Tray 30pcs',
    unitAr: 'كرتونة 30 بيضة',
    costPrice: 15,
    sellingPrice: 22,
    minStock: 30,
    maxStock: 150,
    reorderPoint: 50,
    currentStock: 80,
    warehouseLocation: 'GR-02-R',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'GRC-003',
    nameEn: 'Mineral Water 1.5L',
    nameAr: 'مياه معدنية 1.5 لتر',
    category: 'Beverages',
    subCategory: 'Water',
    industry: ['Grocery Store', 'Small Retail', 'Supermarket'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 1.5,
    sellingPrice: 2.5,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 400,
    currentStock: 1000,
    warehouseLocation: 'GR-03-D',
    barcode: '6286666666662',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'GRC-004',
    nameEn: 'Potato Chips 150g',
    nameAr: 'شيبس بطاطس 150 جرام',
    category: 'Snacks',
    subCategory: 'Chips',
    industry: ['Grocery Store', 'Small Retail', 'Supermarket'],
    type: 'merchandise',
    unit: 'Bag',
    unitAr: 'كيس',
    costPrice: 4,
    sellingPrice: 7,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'GR-04-D',
    barcode: '6286666666663',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'GRC-005',
    nameEn: 'Toilet Paper 4 Rolls',
    nameAr: 'مناديل حمام 4 لفات',
    category: 'Household',
    subCategory: 'Paper Products',
    industry: ['Grocery Store', 'Small Retail', 'Supermarket'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'حزمة',
    costPrice: 8,
    sellingPrice: 12,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'GR-05-D',
    barcode: '6286666666664',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // ==============================================
  // 13. GENERAL SUPERMARKET (محال التجزئة)
  // ==============================================
  
  {
    code: 'SUP-001',
    nameEn: 'Fresh Apples Red',
    nameAr: 'تفاح أحمر طازج',
    category: 'Fresh Produce',
    subCategory: 'Fruits',
    industry: ['Supermarket', 'Grocery Store'],
    type: 'merchandise',
    unit: 'Kg',
    unitAr: 'كجم',
    costPrice: 8,
    sellingPrice: 12,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 100,
    currentStock: 150,
    warehouseLocation: 'SP-01-F',
    expiryTracking: true,
    batchTracking: false,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'SUP-002',
    nameEn: 'Laundry Detergent 3L',
    nameAr: 'مسحوق غسيل 3 لتر',
    category: 'Household',
    subCategory: 'Cleaning',
    industry: ['Supermarket', 'Grocery Store'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 22,
    sellingPrice: 35,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'SP-02-D',
    barcode: '6287777777771',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'SUP-003',
    nameEn: 'Diapers Size 4 (40 pcs)',
    nameAr: 'حفاضات مقاس 4 (40 قطعة)',
    category: 'Baby Care',
    subCategory: 'Diapers',
    industry: ['Supermarket', 'Pharmacy'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'علبة',
    costPrice: 48,
    sellingPrice: 75,
    minStock: 30,
    maxStock: 300,
    reorderPoint: 60,
    currentStock: 150,
    warehouseLocation: 'SP-03-D',
    barcode: '6287777777772',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 0,
    status: 'active',
  },
  {
    code: 'SUP-004',
    nameEn: 'Frozen Pizza Margherita',
    nameAr: 'بيتزا مارجريتا مجمدة',
    category: 'Frozen Food',
    subCategory: 'Ready Meals',
    industry: ['Supermarket'],
    type: 'merchandise',
    unit: 'Piece',
    unitAr: 'قطعة',
    costPrice: 18,
    sellingPrice: 30,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 100,
    currentStock: 150,
    warehouseLocation: 'SP-04-F',
    barcode: '6287777777773',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'SUP-005',
    nameEn: 'Batteries AA Pack of 4',
    nameAr: 'بطاريات AA عبوة 4 قطع',
    category: 'Electronics',
    subCategory: 'Batteries',
    industry: ['Supermarket', 'Electronics Store'],
    type: 'merchandise',
    unit: 'Pack',
    unitAr: 'علبة',
    costPrice: 8,
    sellingPrice: 15,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'SP-05-D',
    barcode: '6287777777774',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },

  // Additional items for comprehensive coverage
  {
    code: 'MISC-001',
    nameEn: 'Printer Paper A4 500 Sheets',
    nameAr: 'ورق طابعة A4 500 ورقة',
    category: 'Office Supplies',
    subCategory: 'Paper',
    industry: ['Office Supplies', 'Stationery'],
    type: 'supplies',
    unit: 'Ream',
    unitAr: 'رزمة',
    costPrice: 15,
    sellingPrice: 25,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 100,
    currentStock: 250,
    warehouseLocation: 'OF-01-D',
    barcode: '6288888888881',
    expiryTracking: false,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
  {
    code: 'MISC-002',
    nameEn: 'Hand Sanitizer 500ml',
    nameAr: 'معقم يدين 500 مل',
    category: 'Health & Safety',
    subCategory: 'Sanitizers',
    industry: ['Pharmacy', 'Supermarket', 'Hospital'],
    type: 'merchandise',
    unit: 'Bottle',
    unitAr: 'زجاجة',
    costPrice: 18,
    sellingPrice: 30,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 200,
    currentStock: 500,
    warehouseLocation: 'HS-01-D',
    barcode: '6288888888882',
    expiryTracking: true,
    batchTracking: true,
    serialTracking: false,
    taxRate: 15,
    status: 'active',
  },
];

// Helper functions
export const getItemByCode = (code: string): InventoryItem | undefined => {
  return universalInventoryItems.find(item => item.code === code);
};

export const getItemsByIndustry = (industry: string): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.industry.includes(industry));
};

export const getItemsByCategory = (category: string): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.category === category);
};

export const getItemsByType = (type: InventoryItem['type']): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.type === type);
};

export const searchItems = (searchTerm: string): InventoryItem[] => {
  const term = searchTerm.toLowerCase();
  return universalInventoryItems.filter(
    item =>
      item.code.toLowerCase().includes(term) ||
      item.nameEn.toLowerCase().includes(term) ||
      item.nameAr.includes(term) ||
      item.category.toLowerCase().includes(term) ||
      item.barcode?.includes(term) ||
      item.sku?.includes(term)
  );
};

export const getLowStockItems = (): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.currentStock <= item.reorderPoint);
};

export const getOutOfStockItems = (): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.currentStock === 0);
};

export const getExpiryTrackingItems = (): InventoryItem[] => {
  return universalInventoryItems.filter(item => item.expiryTracking);
};

export const calculateTotalInventoryValue = (): number => {
  return universalInventoryItems.reduce(
    (total, item) => total + (item.costPrice * item.currentStock),
    0
  );
};

// Industry categories for filtering
export const industryCategories = [
  'Chemical Manufacturing',
  'Food Manufacturing',
  'Construction Manufacturing',
  'Mining',
  'Metal Manufacturing',
  'Food Retail',
  'Cosmetics Retail',
  'Auto Parts',
  'Hospital',
  'Clinic',
  'Pharmacy',
  'Restaurant',
  'Catering',
  'IT Services',
  'Telecom',
  'Construction',
  'Contracting',
  'Grocery Store',
  'Small Retail',
  'Supermarket',
  'Hardware Store',
];

// Item types for classification
export const itemTypes = [
  { value: 'raw_material', labelEn: 'Raw Material', labelAr: 'مواد خام' },
  { value: 'wip', labelEn: 'Work in Progress', labelAr: 'إنتاج تحت التشغيل' },
  { value: 'finished_goods', labelEn: 'Finished Goods', labelAr: 'منتجات تامة' },
  { value: 'merchandise', labelEn: 'Merchandise', labelAr: 'بضائع للبيع' },
  { value: 'spare_parts', labelEn: 'Spare Parts', labelAr: 'قطع غيار' },
  { value: 'consumables', labelEn: 'Consumables', labelAr: 'مستهلكات' },
  { value: 'supplies', labelEn: 'Supplies', labelAr: 'مستلزمات' },
];